begin;
create temporary table staff_test_result(name text);
create temporary table staff_test_admin as select user_id from public.hp_user_facilities where role='ADMIN' limit 1;
grant select on staff_test_admin to authenticated;
create temporary table staff_test_identity as select row_number() over(order by pa.user_id) n,pa.user_id,pa.personnel_id,p.facility_code from public.hp_personnel_accounts pa join public.hp_personnel p on p.id=pa.personnel_id where p.active and not exists(select 1 from public.hp_user_facilities uf where uf.user_id=pa.user_id and uf.role='ADMIN') limit 2;
grant select on staff_test_identity to authenticated;
insert into public.hp_staff_documents(owner_user_id,personnel_id,facility_code,form_code,fiscal_year,template_version,form_data) values((select user_id from staff_test_identity where staff_test_identity.n=1),(select personnel_id from staff_test_identity where staff_test_identity.n=1),(select facility_code from staff_test_identity where staff_test_identity.n=1),'chor11_annual',2569,'2569.1','{}');
insert into public.hp_staff_documents(owner_user_id,personnel_id,facility_code,form_code,fiscal_year,period_month,template_version,form_data) values((select user_id from staff_test_identity where staff_test_identity.n=1),(select personnel_id from staff_test_identity where staff_test_identity.n=1),(select facility_code from staff_test_identity where staff_test_identity.n=1),'chor11_monthly',2569,'2026-09-01','2569.1','{}');
grant all on staff_test_result to authenticated;
set local role anon;
do $$ begin if exists(select 1 from public.hp_staff_documents) then raise exception 'Guest can read'; end if; exception when insufficient_privilege then null; end $$;
reset role;
insert into staff_test_result values('guest SELECT blocked');
set local role authenticated;
select set_config('request.jwt.claims',jsonb_build_object('sub',(select user_id from staff_test_admin),'role','authenticated')::text,true);
do $$ declare count_rows int; begin select count(*) into count_rows from public.hp_staff_documents; if count_rows<>2 then raise exception 'ADMIN cannot see all'; end if; delete from public.hp_staff_documents; get diagnostics count_rows=row_count; if count_rows<>0 then raise exception 'ADMIN deleted other owner'; end if; insert into staff_test_result values('ADMIN SELECT all and DELETE other owner blocked'); end $$;
select set_config('request.jwt.claims',(select jsonb_build_object('sub',user_id,'role','authenticated')::text from staff_test_identity where staff_test_identity.n=2),true);
do $$ begin if exists(select 1 from public.hp_staff_documents) then raise exception 'Cross owner visibility'; end if; insert into staff_test_result values('cross-owner SELECT blocked'); end $$;
select set_config('request.jwt.claims',(select jsonb_build_object('sub',user_id,'role','authenticated')::text from staff_test_identity where staff_test_identity.n=1),true);
do $$ declare n int; begin
 select count(*) into n from public.hp_staff_documents; if n<>2 then raise exception 'Own documents missing'; end if;
 insert into staff_test_result values('owner SELECT own rows');
 begin insert into public.hp_staff_documents(owner_user_id,personnel_id,facility_code,form_code,fiscal_year,form_data) select owner_user_id,personnel_id,facility_code,form_code,fiscal_year,form_data from public.hp_staff_documents where form_code='chor11_annual'; raise exception 'Annual duplicate accepted'; exception when unique_violation then insert into staff_test_result values('annual duplicate rejected'); end;
 begin insert into public.hp_staff_documents(owner_user_id,personnel_id,facility_code,form_code,fiscal_year,period_month,form_data) select owner_user_id,personnel_id,facility_code,form_code,fiscal_year,period_month,form_data from public.hp_staff_documents where form_code='chor11_monthly'; raise exception 'Monthly duplicate accepted'; exception when unique_violation then insert into staff_test_result values('monthly duplicate rejected'); end;
 begin update public.hp_staff_documents set form_data=form_data||'{"citizen_id":"test"}'; raise exception 'Sensitive key accepted'; exception when check_violation then insert into staff_test_result values('sensitive key rejected'); end;
 begin update public.hp_staff_documents set form_data=form_data||'{"birth_date":"2000-01-01"}'; raise exception 'DOB accepted'; exception when check_violation then insert into staff_test_result values('DOB rejected'); end;
 begin update public.hp_staff_documents set owner_user_id=(select user_id from staff_test_identity where staff_test_identity.n=2); raise exception 'Identity mutation accepted'; exception when insufficient_privilege then insert into staff_test_result values('identity immutable'); end;
 begin update public.hp_staff_documents set period_month='2026-10-01' where form_code='chor11_monthly'; raise exception 'Fiscal mismatch accepted'; exception when check_violation then insert into staff_test_result values('fiscal mismatch rejected'); end;
 delete from public.hp_staff_documents where form_code='chor11_monthly'; get diagnostics n=row_count; if n<>0 then raise exception 'Monthly deleted'; end if; insert into staff_test_result values('monthly DELETE blocked');
 delete from public.hp_staff_documents where form_code='chor11_annual'; get diagnostics n=row_count; if n<>1 then raise exception 'Annual delete failed'; end if; insert into staff_test_result values('own annual DELETE allowed');
end $$;
reset role;
select jsonb_agg(name) as passed from staff_test_result;
rollback;
