import {canManagePersonnel,editablePersonnelUnits} from './permissions.js';
import {personnelGroups,workGroupMembers} from './grouping.js';
import {rest,currentSession,onSession} from '../api/supabase/client.js';
import {escapeHtml as e} from '../utils/core.js';
import {canUploadPhoto,uploadPhoto,signPhotos,signedPhotoUrl} from './photos.js';
const workGroups=[['administration','กลุ่มบริหารสาธารณสุข'],['prevention','กลุ่มส่งเสริมป้องกันควบคุม'],['family_practice','กลุ่มเวชปฏิบัติครอบครัว']];
const icon='<svg viewBox="0 0 48 48" aria-hidden="true"><circle cx="24" cy="15" r="8"/><path d="M8 43v-6c0-17 32-17 32 0v6"/></svg>';
let ctx,tab='structure',search='',unit='',job='',notice='';const cache=new Map();onSession(()=>cache.clear());
try{if(localStorage.getItem('khp-personnel-layout')==='legacy')tab='legacy';}catch{}
const admin=()=>!!currentSession()&&ctx.permissions().some(p=>p.role==='ADMIN');
const editable=p=>!!currentSession()&&canManagePersonnel(ctx.permissions(),p);
const allowedUnits=()=>currentSession()?editablePersonnelUnits(ctx.permissions(),ctx.facilities()):[];
const may=p=>canUploadPhoto(p,ctx.permissions(),ctx.links(),currentSession()?.user.id);
function card(p){const c=cache.get(p.id);return `<article class="person-card"><button class="person-avatar" data-person-avatar="${p.id}" ${may(p)?`data-person-photo="${p.id}" aria-label="อัปโหลดรูป ${e(p.full_name)}"`:'disabled'}>${c?`<img src="${e(c.url)}" alt="${e(p.full_name)}" loading="lazy">`:icon}${may(p)?'<span>เปลี่ยนรูป</span>':''}</button><div class="person-info"><h3>${e(p.full_name)}</h3><p>${e(p.position_name)}${p.position_level?`<span class="person-level">${e(p.position_level)}</span>`:''}</p><p class="subtle">${e(p.employment_type)}</p>${!p.published?'<span class="badge near">รอเผยแพร่</span>':''}${editable(p)?`<button data-person-edit="${p.id}">${admin()?'แก้ไข / เชื่อมบัญชี':'แก้ไขบุคลากร'}</button>`:''}</div></article>`;}
function groupedCards(rows){const groups=personnelGroups(rows);return '<section class="person-position person-unit-head"><h3>หัวหน้าหน่วยบริการ</h3>'+ (groups.heads.map(card).join('')||'<p class="subtle">ยังไม่ได้ระบุหัวหน้าหน่วยบริการ</p>')+'</section>'+groups.positions.map(g=>'<section class="person-position"><h3>'+e(g.title)+' <small>('+g.members.length+' ราย)</small></h3>'+g.members.map(card).join('')+'</section>').join('');}
function leader(role,title){const p=ctx.rows().find(p=>p.active&&p.structure_role===role);return `<section class="person-leader"><h2>${title}</h2>${p?card(p):`<div class="person-vacant">${icon}<p>ยังไม่ได้ระบุผู้ดำรงตำแหน่ง</p>${admin()?`<button data-person-add="${role}">+ ระบุผู้ดำรงตำแหน่ง</button>`:''}</div>`}</section>`;}
function unitDirectory(members){return '<div class="person-directory">'+ctx.facilities().filter(f=>f.active!==false&&(!unit||f.facility_code===unit)&&(ctx.facility()==='all'||ctx.facility()===f.facility_code)).filter(f=>!(search||job)||members.some(p=>p.facility_code===f.facility_code)).map(f=>{const rows=ctx.rows().filter(p=>p.active&&p.facility_code===f.facility_code&&!['director','head'].includes(p.structure_role));const heads=personnelGroups(rows).heads;return '<section class="person-group person-unit-summary"><h2>'+e(f.facility_name)+'</h2><p class="subtle">บุคลากร '+rows.length+' ราย'+((search||job)?' • ตรงตัวกรอง '+members.filter(p=>p.facility_code===f.facility_code).length+' ราย':'')+'</p><h3 class="person-head-label">หัวหน้าศูนย์บริการสาธารณสุข</h3>'+(heads.length?heads.map(card).join(''):'<div class="person-vacant">'+icon+'<p>ยังไม่ได้ระบุหัวหน้าศูนย์</p></div>')+'<a class="person-unit-link" href="#unit/'+encodeURIComponent(f.facility_code)+'/team">ดูบุคลากรของหน่วย →</a></section>';}).join('')+'</div>';}
export function personnelView(context){ctx=context;const selected=ctx.rows().filter(p=>p.active&&(['director','head'].includes(p.structure_role)||ctx.facility()==='all'||p.facility_code===ctx.facility())&&(!unit||p.facility_code===unit)&&(!job||p.position_name===job)&&(!search||(p.full_name+' '+p.position_name).toLowerCase().includes(search.toLowerCase())));const members=selected.filter(p=>!['director','head'].includes(p.structure_role));const jobs=[...new Set(ctx.rows().map(p=>p.position_name).filter(Boolean))].sort();
return `<section class="panel personnel-panel"><div class="panel-heading"><div><h2>บุคลากรและโครงสร้างหน่วยงาน</h2><p class="subtle">กดรูปเพื่อเปลี่ยนภาพตามสิทธิ์ · ต้นฉบับไม่เกิน 2 MB · ย่อจัดเก็บไม่เกิน 100 KB · เก็บ 1 ภาพต่อคน</p></div>${allowedUnits().length?'<button class="primary" data-person-add="member">+ เพิ่มบุคลากร</button>':''}</div>${notice?`<div class="notice" role="status">${e(notice)}</div>`:''}<div class="controls"><label>ค้นหาชื่อ / ตำแหน่ง<input id="person-search" value="${e(search)}" placeholder="ค้นหาบุคลากร"></label><label>หน่วยบริการ<select id="person-unit"><option value="">ทุกหน่วยบริการ</option>${ctx.facilities().map(f=>`<option value="${f.facility_code}" ${unit===f.facility_code?'selected':''}>${e(f.short_name)}</option>`).join('')}</select></label><label>วิชาชีพ / ตำแหน่ง<select id="person-job"><option value="">ทุกตำแหน่ง</option>${jobs.map(j=>`<option ${job===j?'selected':''}>${e(j)}</option>`).join('')}</select></label></div><div class="profile-tabs"><button data-person-tab="structure" aria-pressed="${tab==='structure'}">โครงสร้างหน่วยงาน</button><button data-person-tab="legacy" aria-pressed="${tab==='legacy'}">โครงสร้างแบบเดิม</button><button data-person-tab="list" aria-pressed="${tab==='list'}">รายชื่อบุคลากร</button></div>${['structure','legacy'].includes(tab)?`<div class="person-leaders">${leader('director','ผู้อำนวยการกองสาธารณสุขและสิ่งแวดล้อม')}${leader('head','หัวหน้าฝ่ายบริการสาธารณสุข')}</div><div class="person-connector" aria-hidden="true"></div>${tab==='structure'?unitDirectory(members):`<div class="person-groups">${ctx.facilities().filter(f=>!unit||f.facility_code===unit).filter(f=>ctx.facility()==='all'||ctx.facility()===f.facility_code).map(f=>{const rows=members.filter(p=>p.facility_code===f.facility_code);return `<section class="person-group"><h2>${e(f.facility_name)}</h2><p class="subtle">${rows.length} รายที่พร้อมแสดงในมุมมองนี้</p>${rows.length?groupedCards(rows):'<div class="empty">ยังไม่มีรายชื่อที่เผยแพร่</div>'}</section>`}).join('')}</div>`}`:`<p class="subtle">${selected.length} ราย</p><div class="person-roster">${selected.filter(p=>['director','head'].includes(p.structure_role)).map(card).join('')}</div><div class="person-groups">${ctx.facilities().map(f=>{const rows=members.filter(p=>p.facility_code===f.facility_code);return rows.length?'<section class="person-group"><h2>'+e(f.facility_name)+'</h2>'+groupedCards(rows)+'</section>':'';}).join('')||'<div class="empty">ไม่พบรายชื่อของหน่วยตามตัวกรอง</div>'}</div>`}${admin()?'<p class="subtle">รายชื่อจาก compensation พักการเผยแพร่ไว้ก่อน เลือกแก้ไขเพื่อเปิดเผยแพร่ และเชื่อม UUID ของบัญชี USER ให้เปลี่ยนรูปตนเอง</p>':''}<input type="file" id="person-photo-file" accept="image/jpeg,image/png,image/webp" hidden></section>`;}
let orgResize;
function mountOrgConnectors(){
 orgResize?.disconnect();
 const root=document.querySelector('.unit-org'),head=root?.querySelector('.unit-org-head'),branches=root?.querySelector('.unit-org-branches');
 if(!root||!head||!branches)return;
 const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.classList.add('unit-org-lines');svg.setAttribute('aria-hidden','true');root.querySelector('.unit-org-lines')?.remove();root.append(svg);
 const draw=()=>{
  svg.replaceChildren();if(matchMedia('(max-width:720px)').matches)return;
  const origin=root.getBoundingClientRect(),h=head.getBoundingClientRect();
  const groups=[...branches.querySelectorAll('.unit-org-group')].map(el=>el.getBoundingClientRect());if(!groups.length)return;
  const top=Math.min(...groups.map(r=>r.top)),targets=groups.filter(r=>Math.abs(r.top-top)<2);
  const x=h.left+h.width/2-origin.left-root.clientLeft,y=h.bottom-origin.top-root.clientTop;
  const bar=top-origin.top-root.clientTop-24;
  const centers=targets.map(r=>r.left+r.width/2-origin.left-root.clientLeft);
  const line=(x1,y1,x2,y2)=>{const el=document.createElementNS(svg.namespaceURI,'line');for(const [k,v] of Object.entries({x1,y1,x2,y2}))el.setAttribute(k,v);svg.append(el);};
  line(x,y-24,x,bar);line(Math.min(x,...centers),bar,Math.max(x,...centers),bar);
  targets.forEach((r,i)=>line(centers[i],bar,centers[i],r.top-origin.top-root.clientTop+2));
 };
 orgResize=new ResizeObserver(draw);orgResize.observe(root);orgResize.observe(head);orgResize.observe(branches);draw();
}
export async function mountPersonnel(){mountOrgConnectors();if(!ctx||!document.querySelector('.personnel-panel'))return;const missing=ctx.rows().filter(p=>p.photo_updated_at&&(!cache.has(p.id)||cache.get(p.id).revision!==p.photo_updated_at||cache.get(p.id).expires<Date.now()));if(!missing.length)return;try{const signed=await signPhotos(missing.map(p=>p.id+'.webp'));signed.forEach(s=>{const p=missing.find(p=>s.path===p.id+'.webp'),path=s.signedURL??s.signedUrl;if(p&&path)cache.set(p.id,{url:signedPhotoUrl(path),revision:p.photo_updated_at,expires:Date.now()+240000});});document.querySelectorAll('[data-person-avatar]').forEach(b=>{const c=cache.get(b.dataset.personAvatar);if(c){const img=document.createElement('img');img.src=c.url;img.alt=ctx.rows().find(p=>p.id===b.dataset.personAvatar)?.full_name??'รูปบุคลากร';img.loading='lazy';const old=b.querySelector('svg,img');old?.replaceWith(img);}});}catch{notice='โหลดภาพบางรายการไม่สำเร็จ กรุณารีเฟรชอีกครั้ง';}}
function edit(id,role='member'){const p=ctx.rows().find(p=>p.id===id)??{structure_role:role,facility_code:['director','head'].includes(role)?null:allowedUnits()[0]?.facility_code};if(!editable(p))return;const link=ctx.links().find(a=>a.personnel_id===id);const field=(name,label,value='',max=200)=>`<label>${label}<input name="${name}" value="${e(value??'')}" ${name==='full_name'?'required':''} maxlength="${max}"></label>`;
ctx.dialog(id?(admin()?'แก้ไขบุคลากร / เชื่อมบัญชี':'แก้ไขบุคลากร'):'เพิ่มบุคลากร',`<form id="person-form" data-id="${id??''}"><div class="form-grid">${field('full_name','ชื่อ–นามสกุล',p.full_name)}${field('position_name','ตำแหน่ง',p.position_name)}${field('position_level','ระดับ',p.position_level,100)}${field('employment_type','ประเภทบุคลากร',p.employment_type,100)}<label>บทบาทในผัง<select name="structure_role">${[['director','ผู้อำนวยการกอง'],['head','หัวหน้าฝ่าย'],['unit_head','หัวหน้าหน่วยบริการ'],['member','บุคลากร']].filter(([v])=>admin()||['unit_head','member'].includes(v)).map(([v,n])=>`<option value="${v}" ${p.structure_role===v?'selected':''}>${n}</option>`).join('')}</select></label><label>กลุ่มงานในผัง<select name="work_group"><option value="">ยังไม่กำหนด / จัดตามวิชาชีพเดิม</option>${workGroups.map(([v,n])=>`<option value="${v}" ${p.work_group===v?'selected':''}>${n}</option>`).join('')}</select></label><label>หน่วยบริการ<select name="facility_code">${admin()?'<option value="">ระดับกอง / ฝ่าย</option>':''}${allowedUnits().filter(f=>admin()||!id||f.facility_code===p.facility_code).map(f=>`<option value="${f.facility_code}" ${p.facility_code===f.facility_code?'selected':''}>${e(f.short_name)}</option>`).join('')}</select></label><label>ลำดับแสดง<input name="display_order" type="number" value="${p.display_order??100}" required></label><label>เผยแพร่ชื่อ / รูป<select name="published"><option value="false" ${!p.published?'selected':''}>พักการแสดงผล</option><option value="true" ${p.published?'selected':''}>แสดงหน้าเว็บ</option></select></label><label>สถานะ<select name="active" ${admin()?'':'disabled'}><option value="true" ${p.active!==false?'selected':''}>ปฏิบัติงาน</option><option value="false" ${p.active===false?'selected':''}>ปิดรายการ</option></select></label>${admin()?field('user_id','เชื่อมบัญชี USER (UUID) — เว้นว่างเพื่อยกเลิก',link?.user_id,36):''}</div><p class="subtle">ADMIN เชื่อมบัญชีตามตัวบุคคล USER เปลี่ยนได้เฉพาะรูปของตนเอง</p><div id="person-error" class="form-error" role="status"></div><button type="submit" class="primary">บันทึก</button></form>`);}
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b||!ctx)return;if(b.dataset.personTab){tab=b.dataset.personTab;if(['structure','legacy'].includes(tab))try{localStorage.setItem('khp-personnel-layout',tab);}catch{}ctx.render();}if(b.dataset.personEdit)edit(b.dataset.personEdit);if(b.dataset.personAdd)edit(null,b.dataset.personAdd);if(b.dataset.personPhoto){const p=ctx.rows().find(p=>p.id===b.dataset.personPhoto);if(!p||!may(p))return;const input=document.getElementById('person-photo-file');input.dataset.personId=p.id;input.click();}});
document.addEventListener('change',async event=>{if(!ctx)return;const el=event.target;if(['person-search','person-unit','person-job'].includes(el.id)){if(el.id==='person-search')search=el.value.trim();if(el.id==='person-unit')unit=el.value;if(el.id==='person-job')job=el.value;ctx.render();}if(el.id==='person-photo-file'&&el.files[0]){const id=el.dataset.personId;notice='กำลังย่อและอัปโหลด…';try{const bytes=await uploadPhoto(id,el.files[0]);cache.delete(id);notice='บันทึกภาพแล้ว '+Math.ceil(bytes/1024)+' KB · ใช้แทนภาพเดิม';await ctx.reload();}catch(error){notice='บันทึกไม่สำเร็จ: '+error.message;ctx.render();ctx.dialog('อัปโหลดรูปไม่สำเร็จ','<p role="alert">'+e(error.message)+'</p>');}finally{el.value='';}}});
document.addEventListener('submit',async event=>{const form=event.target;if(form.id!=='person-form')return;event.preventDefault();const b=form.querySelector('button[type=submit]');b.disabled=true;try{const original=ctx.rows().find(p=>p.id===form.dataset.id);if(original&&!editable(original))throw new Error('ไม่มีสิทธิ์แก้ไขหน่วยนี้');const v=Object.fromEntries(new FormData(form)),user=(v.user_id??'').trim();delete v.user_id;v.full_name=v.full_name.trim();v.facility_code=v.facility_code||null;v.display_order=Number(v.display_order);v.published=v.published==='true';v.active=admin()?v.active==='true':original?.active??true;if(!editable(v))throw new Error('ไม่มีสิทธิ์แก้ไขหน่วยนี้');if(!admin()&&original&&v.facility_code!==original.facility_code)throw new Error('ไม่อนุญาตให้ย้ายหน่วย');if(!v.facility_code&&!['director','head'].includes(v.structure_role))throw new Error('เลือกหน่วยบริการ');if(user&&!/^[0-9a-f-]{36}$/i.test(user))throw new Error('UUID บัญชีไม่ถูกต้อง');const rows=await rest('hp_personnel',form.dataset.id?'id=eq.'+form.dataset.id:'',form.dataset.id?'PATCH':'POST',v);const id=rows[0]?.id;if(!id)throw new Error('บันทึกไม่สำเร็จ');const existing=ctx.links().find(a=>a.personnel_id===id);if(admin()&&user)await rest('hp_personnel_accounts',existing?'personnel_id=eq.'+id:'',existing?'PATCH':'POST',{personnel_id:id,user_id:user});else if(admin()&&existing)await rest('hp_personnel_accounts','personnel_id=eq.'+id,'DELETE');ctx.closeDialog();notice='บันทึกรายการบุคลากรแล้ว';await ctx.reload();}catch(error){const target=form.querySelector('#person-error');if(form.isConnected&&target)target.textContent=error.message;else{notice='บันทึกไม่สำเร็จ: '+error.message;ctx.render();}}finally{b.disabled=false;}});

function unitStructureRows(positions){
 const assigned=positions.flatMap(g=>g.members).filter(p=>p.work_group);
 let workHtml='';
 if(assigned.length){workHtml='<div class="unit-work-groups">'+workGroups.map(([key,label],i)=>{const rows=assigned.filter(p=>p.work_group===key);return rows.length?'<section class="unit-org-group unit-org-color-'+i+' "><h3>'+label+' <small>('+rows.length+' ราย)</small></h3><div class="unit-org-members">'+workGroupMembers(rows).map(card).join('')+'</div></section>':'';}).join('')+'</div>';positions=positions.map(g=>({...g,members:g.members.filter(p=>!p.work_group)})).filter(g=>g.members.length);}

 const buckets=[[],[],[]];
 for(const g of positions){let row=2,column=buckets[2].length%2;if(/^พยาบาล/.test(g.title)){row=0;column=0;}else if(/^(?:นักวิชาการ|เจ้าพนักงาน|จพง\.?\s*)/.test(g.title)){row=0;column=1;}else if(/^ผู้ช่วยเจ้าพนักงานธุรการ/.test(g.title)){row=1;column=0;}else if(/^เจ้าหน้าที่สำรวจข้อมูล/.test(g.title)){row=1;column=1;}buckets[row].push({g,column});}
 return workHtml+buckets.filter(items=>items.length).map(items=>'<div class="unit-org-row">'+[0,1].map(column=>'<div class="unit-org-column">'+items.filter(item=>item.column===column).map(({g})=>'<section class="unit-org-group unit-org-color-'+column+'"><h3>'+e(g.title)+' <small>('+g.members.length+' ราย)</small></h3><div class="unit-org-members">'+g.members.map(card).join('')+'</div></section>').join('')+'</div>').join('')+'</div>').join('');
}
export function unitPersonnel(context){ctx=context;const rows=ctx.rows(),groups=personnelGroups(rows),facility=ctx.facilities().find(f=>f.facility_code===ctx.facility());if(!rows.length)return '<div class="personnel-panel empty">ยังไม่มีรายชื่อบุคลากรที่เผยแพร่สำหรับหน่วยนี้</div>';return '<div class="personnel-panel unit-org"><h2 class="unit-org-banner">โครงสร้างบุคลากร '+e(facility?.facility_name??'หน่วยบริการ')+'</h2><section class="unit-org-head" aria-label="หัวหน้าศูนย์"><h3>หัวหน้าศูนย์บริการสาธารณสุข</h3>'+(groups.heads.map(card).join('')||'<p class="person-vacant">ยังไม่ได้ระบุหัวหน้าศูนย์</p>')+'</section><div class="unit-org-branches">'+unitStructureRows(groups.positions)+'</div></div>';}
