import test from 'node:test';import assert from 'node:assert/strict';
import {handleRequest} from '../supabase/functions/hp-accounts/core.js';
const env={SUPABASE_URL:'https://test.invalid',SUPABASE_SERVICE_ROLE_KEY:'server-only-fixture'};
const make=(body,auth=true)=>new Request('https://test.invalid/hp-accounts',{method:'POST',headers:{Origin:'https://kelang-health.github.io','Content-Type':'application/json',...(auth?{Authorization:'Bearer test-session'}:{})},body:JSON.stringify(body)});
function upstream({admin=true,managed=true,active=false,failAssignment=false}={}){const calls=[];const fetcher=async(url,options)=>{const path=new URL(url).pathname;calls.push({path,method:options.method,body:options.body?JSON.parse(options.body):undefined});let d=[];let status=200;if(path==='/auth/v1/user')d={id:'actor'};else if(path==='/rest/v1/hp_user_facilities'&&options.method==='GET')d=admin?[{role:'ADMIN'}]:[];else if(path==='/rest/v1/hp_facilities')d=[{facility_code:'06116'},{facility_code:'06117'}];else if(path==='/auth/v1/admin/users'&&options.method==='POST')d={id:'new-user'};else if(path==='/rest/v1/profiles')d=[{active,role:'STAFF'}];else if(path==='/auth/v1/admin/users/00000000-0000-0000-0000-000000000002')d={app_metadata:{hp_only:managed}};else if(path==='/rest/v1/hp_user_facilities'&&options.method==='POST'&&failAssignment){status=500;d={error:'failed'};}return new Response(JSON.stringify(d),{status});};return {fetcher,calls};}
test('Unauthenticated and STAFF cannot use account administration',async()=>{assert.equal((await handleRequest(make({action:'create'},false),env)).status,401);const u=upstream({admin:false});assert.equal((await handleRequest(make({action:'create'}),env,u.fetcher)).status,403);assert.ok(!u.calls.some(c=>c.path.includes('/admin/users')));});
test('Create only new HP-marked accounts with inactive profile and scoped assignments',async()=>{const u=upstream();const r=await handleRequest(make({action:'create',email:'staff@example.test',password:'test-only-password-123',name:'Test',role:'STAFF',facilities:['06116']}),env,u.fetcher);assert.equal(r.status,201);const body=u.calls.find(c=>c.path==='/auth/v1/admin/users').body;assert.equal(body.app_metadata.hp_only,true);assert.deepEqual(u.calls.find(c=>c.path==='/rest/v1/hp_user_facilities'&&c.method==='POST').body,[{user_id:'new-user',facility_code:'06116',role:'STAFF'}]);assert.ok(!u.calls.some(c=>c.path==='/rest/v1/profiles'&&c.method!=='GET'));assert.ok(u.calls.filter(c=>c.path==='/rest/v1/hp_audit_logs').every(c=>!JSON.stringify(c.body).includes('test-only-password')));});
test('Reset rejects existing shared-system accounts',async()=>{const u=upstream({managed:false});const r=await handleRequest(make({action:'reset_password',user_id:'00000000-0000-0000-0000-000000000002',password:'test-only-password-123'}),env,u.fetcher);assert.equal(r.status,403);assert.ok(!u.calls.some(c=>c.method==='PUT'));});
test('Failed assignment removes only the freshly created account',async()=>{const u=upstream({failAssignment:true});const r=await handleRequest(make({action:'create',email:'staff@example.test',password:'test-only-password-123',name:'Test',role:'STAFF',facilities:['06116']}),env,u.fetcher);assert.equal(r.status,500);assert.ok(u.calls.some(c=>c.path==='/auth/v1/admin/users/new-user'&&c.method==='DELETE'));});
test('Invalid facilities never create an account',async()=>{const u=upstream();const r=await handleRequest(make({action:'create',email:'staff@example.test',password:'test-only-password-123',name:'Test',role:'STAFF',facilities:['99999']}),env,u.fetcher);assert.equal(r.status,400);assert.ok(!u.calls.some(c=>c.path==='/auth/v1/admin/users'));});
test('USER creation assigns no facility privileges or rights in other apps',async()=>{const u=upstream();const r=await handleRequest(make({action:'create',email:'user@example.test',password:'test-only-password-123',name:'Self',role:'USER',facilities:[]}),env,u.fetcher);assert.equal(r.status,201);assert.equal(u.calls.find(c=>c.path==='/auth/v1/admin/users').body.app_metadata.hp_account_role,'USER');assert.ok(!u.calls.some(c=>c.path==='/rest/v1/hp_user_facilities'&&c.method==='POST'));});
