import test from 'node:test';import assert from 'node:assert/strict';
import {personnelGroups} from '../src/personnel/grouping.js';
test('Sri Muad Klao abbreviated public health officer follows nurses and optional academics',()=>{const titles=['เจ้าหน้าที่สำรวจข้อมูล','จพง.สาธารณสุข','ผู้ช่วยเจ้าพนักงานธุรการ','นักวิชาการสาธารณสุข','พยาบาลวิชาชีพ'];const rows=titles.map(position_name=>({position_name,facility_code:'06118',structure_role:'member'}));rows.push({position_name:'พยาบาลวิชาชีพ',facility_code:'06118',structure_role:'unit_head'});const groups=personnelGroups(rows);assert.equal(groups.heads.length,1);assert.deepEqual(groups.positions.map(g=>g.title),['พยาบาลวิชาชีพ','นักวิชาการสาธารณสุข','จพง.สาธารณสุข','ผู้ช่วยเจ้าพนักงานธุรการ','เจ้าหน้าที่สำรวจข้อมูล']);assert.equal(personnelGroups(rows.filter(r=>!r.position_name.startsWith('นักวิชาการ'))).positions.length,4);});
test('Unit heads lead despite display order, positions group irrespective of input order',()=>{
 const m=personnelGroups([{full_name:'ข',position_name:'พยาบาลวิชาชีพ',structure_role:'member',display_order:2},{full_name:'ค',position_name:'จ้างเหมา',structure_role:'member',display_order:0},{full_name:'หัวหน้า',position_name:'พยาบาลวิชาชีพ',structure_role:'unit_head',display_order:999},{full_name:'ก',position_name:'พยาบาลวิชาชีพ',structure_role:'member',display_order:1},{full_name:'ง',position_name:'นักวิชาการสาธารณสุข',structure_role:'member'}]);
 assert.equal(m.heads[0].full_name,'หัวหน้า');assert.deepEqual(m.positions.map(g=>g.title),['พยาบาลวิชาชีพ','นักวิชาการสาธารณสุข','จ้างเหมา']);assert.deepEqual(m.positions[0].members.map(p=>p.full_name),['ก','ข']);assert.equal(m.positions.flatMap(g=>g.members).some(p=>p.structure_role==='unit_head'),false);
});
test('Position seniority alone never assigns unit head',()=>{assert.equal(personnelGroups([{position_name:'พยาบาลวิชาชีพ',position_level:'ชำนาญการพิเศษ',structure_role:'member'}]).heads.length,0);});

test('Civil servants precede employees within a profession, then Thai names ignoring titles and manual order',()=>{const rows=[{full_name:'นาย อภิวันท์',employment_type:'ข้าราชการ',display_order:999},{full_name:'นางสาว เบญจพร',employment_type:'พนักงานจ้าง',display_order:0},{full_name:'นาย วิสารัตน์',employment_type:'พนักงานจ้าง',display_order:0},{full_name:'นาง กนก',employment_type:'ข้าราชการ',display_order:999}].map(p=>({...p,position_name:'นักวิชาการสาธารณสุข',structure_role:'member'}));assert.deepEqual(personnelGroups(rows).positions[0].members.map(p=>p.full_name),['นาง กนก','นาย อภิวันท์','นางสาว เบญจพร','นาย วิสารัตน์']);});

test('Requested six profession groups follow unit head and precede other positions',()=>{const titles=['จ้างเหมา','พนักงานบริการทั่วไป','เจ้าหน้าที่สำรวจข้อมูล','เจ้าพนักงานสาธารณสุข','ผู้ช่วยเจ้าพนักงานธุรการ','นักวิชาการสาธารณสุข','พยาบาลวิชาชีพ'];const m=personnelGroups(titles.map(position_name=>({position_name,full_name:'นาย ก',structure_role:'member'})));assert.deepEqual(m.positions.map(g=>g.title),['พยาบาลวิชาชีพ','นักวิชาการสาธารณสุข','เจ้าพนักงานสาธารณสุข','ผู้ช่วยเจ้าพนักงานธุรการ','เจ้าหน้าที่สำรวจข้อมูล','พนักงานบริการทั่วไป','จ้างเหมา']);});

test('Kelang Nakorn personnel follow the requested 11-level display order',()=>{const titles=['เจ้าหน้าที่สำรวจข้อมูล','ผู้ช่วยเจ้าพนักงานธุรการ','เจ้าหน้าที่กู้ชีพ','เจ้าพนักงานทันตสาธารณสุข','นักกายภาพบำบัด','แพทย์แผนไทย','พยาบาลวิชาชีพ','เภสัชกร','ทันตแพทย์','แพทย์'];const rows=[{full_name:'หัวหน้า',position_name:'พยาบาลวิชาชีพ',structure_role:'unit_head',facility_code:'45030'},...titles.map(position_name=>({position_name,full_name:'นาย ก',structure_role:'member',facility_code:'45030'}))];const m=personnelGroups(rows);assert.equal(m.heads[0].full_name,'หัวหน้า');assert.deepEqual(m.positions.map(g=>g.title),['แพทย์','ทันตแพทย์','เภสัชกร','พยาบาลวิชาชีพ','แพทย์แผนไทย','นักกายภาพบำบัด','เจ้าพนักงานทันตสาธารณสุข','เจ้าหน้าที่กู้ชีพ','ผู้ช่วยเจ้าพนักงานธุรการ','เจ้าหน้าที่สำรวจข้อมูล']);});
test('Kelang Nakorn does not render empty doctor or dentist groups',()=>{const rows=[{full_name:'หัวหน้า',position_name:'พยาบาลวิชาชีพ',structure_role:'unit_head',facility_code:'45030'},{full_name:'ก',position_name:'เภสัชกร',structure_role:'member',facility_code:'45030'},{full_name:'ข',position_name:'พยาบาลวิชาชีพ',structure_role:'member',facility_code:'45030'}];const m=personnelGroups(rows);assert.deepEqual(m.positions.map(g=>g.title),['เภสัชกร','พยาบาลวิชาชีพ']);assert.equal(m.positions.some(g=>/^แพทย์$|^ทันตแพทย์$/.test(g.title)),false);});
test('Kelang Nakorn special order does not alter other service units',()=>{const rows=['เจ้าหน้าที่สำรวจข้อมูล','เภสัชกร','พยาบาลวิชาชีพ'].map(position_name=>({position_name,full_name:'นาย ก',structure_role:'member',facility_code:'06116'}));const m=personnelGroups(rows);assert.deepEqual(m.positions.map(g=>g.title),['พยาบาลวิชาชีพ','เจ้าหน้าที่สำรวจข้อมูล','เภสัชกร']);});
