import test from 'node:test';import assert from 'node:assert/strict';
import {sessionPolicy,sessionStatus} from '../src/api/supabase/session-policy.js';
let sequence=0;
test('logout clears local identity even when Auth rejects an expired token',async t=>{const original=globalThis.fetch;t.after(()=>globalThis.fetch=original);globalThis.fetch=async()=>Response.json({message:'token is expired'},{status:403});const c=await client(session());await c.logout();assert.equal(c.currentSession(),null);});
async function client(value){const values=new Map(value?[['khp-session',JSON.stringify(value)]]:[]);globalThis.sessionStorage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};return import('../src/api/supabase/client.js?timeout-test='+ ++sequence);}
const session=()=>({access_token:'test-token',refresh_token:'test-refresh',expires_at:Date.now()/1000+3600,hp_started_at:Date.now(),hp_last_active_at:Date.now(),user:{id:'test-user'}});
test('idle warning precedes expiry and activity cannot extend the absolute deadline',()=>{const now=Date.now();let value={hp_started_at:now-7*3600000,hp_last_active_at:now-29*60000};assert.equal(sessionStatus(value,now).remaining,60000);assert.equal(sessionStatus(value,now).reason,'idle');value={hp_started_at:now-sessionPolicy.maxMs,hp_last_active_at:now};assert.equal(sessionStatus(value,now).remaining,0);assert.equal(sessionStatus(value,now).reason,'maximum');assert.equal(sessionStatus({},now).reason,'legacy');});
test('expired idle session cannot revive by user activity or send a write',async t=>{const original=globalThis.fetch;t.after(()=>globalThis.fetch=original);const calls=[];globalThis.fetch=async url=>{calls.push(String(url));return new Response(null,{status:204});};const c=await client({...session(),hp_last_active_at:Date.now()-sessionPolicy.idleMs});c.recordSessionActivity();assert.equal(c.currentSession(),null);assert.equal(c.sessionExpiryReason(),'idle');await assert.rejects(c.rest('hp_settings','','POST',{}),/เข้าสู่ระบบ/);assert.ok(calls.every(x=>x.includes('/logout?scope=local')));});
test('refresh preserves signin and human activity clocks instead of prolonging login',async t=>{const original=globalThis.fetch;t.after(()=>globalThis.fetch=original);const initial={...session(),expires_at:0};globalThis.fetch=async()=>Response.json({access_token:'new-token',refresh_token:'new-refresh',expires_in:3600,user:{id:'test-user'}});const c=await client(initial);await c.refreshSession();assert.equal(c.currentSession().hp_started_at,initial.hp_started_at);assert.equal(c.currentSession().hp_last_active_at,initial.hp_last_active_at);});
test('background reads do not touch or restart idle clock',async t=>{const original=globalThis.fetch;t.after(()=>globalThis.fetch=original);const urls=[];globalThis.fetch=async url=>{urls.push(String(url));return Response.json([]);};const initial=session();const c=await client(initial);await c.loadProfile();assert.equal(c.currentSession().hp_last_active_at,initial.hp_last_active_at);assert.ok(!urls.some(x=>x.includes('hp_touch_session')));});
test('server denies heartbeat and local identity is removed',async t=>{const original=globalThis.fetch;t.after(()=>globalThis.fetch=original);globalThis.fetch=async()=>Response.json({message:'HP_SESSION_EXPIRED'},{status:403});const c=await client(session());await assert.rejects(c.touchSession(true));assert.equal(c.currentSession(),null);assert.equal(c.sessionExpiryReason(),'server');});
test('new login requires server registration and uses the server signin time',async t=>{const original=globalThis.fetch;t.after(()=>globalThis.fetch=original);const started=Date.now()-10000;globalThis.fetch=async url=>String(url).includes('grant_type=password')?Response.json({access_token:'new-login',expires_in:3600,user:{id:'test-user'}}):Response.json({started_at:new Date(started).toISOString()});const c=await client(null);await c.login('fixture@example.invalid','fixture-password');assert.equal(c.currentSession().hp_started_at,started);});
