import test from 'node:test';import assert from 'node:assert/strict';
let sequence=0;
async function auth(expires=Date.now()/1000-1){const value={access_token:'test-old',refresh_token:'test-refresh',expires_at:expires,user:{id:'fixture'}};const storage=new Map([['khp-session',JSON.stringify(value)]]);globalThis.sessionStorage={getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)};return import('../src/api/supabase/client.js?test='+ ++sequence);}
const token={access_token:'test-new',refresh_token:'test-next',expires_in:3600,user:{id:'fixture'}};
test('concurrent profile reads refresh once and all use the new token',async t=>{const original=globalThis.fetch;t.after(()=>globalThis.fetch=original);const client=await auth();let refreshes=0;globalThis.fetch=async(url,options)=>{if(String(url).includes('grant_type=refresh_token')){refreshes++;await new Promise(r=>setTimeout(r,10));return Response.json(token);}assert.equal(options.headers.Authorization,'Bearer test-new');return Response.json([]);};const r=await client.loadProfile();assert.equal(refreshes,1);assert.equal(r.errors.length,0);assert.equal(Object.keys(r.tables).length,14);});
test('logout during refresh never restores a cleared session',async t=>{const original=globalThis.fetch;t.after(()=>globalThis.fetch=original);const client=await auth();let release;globalThis.fetch=async url=>String(url).includes('grant_type=refresh_token')?new Promise(r=>release=()=>r(Response.json(token))):new Response(null,{status:204});const pending=client.refreshSession();await client.logout();assert.equal(client.currentSession(),null);release();await pending;assert.equal(client.currentSession(),null);assert.equal(sessionStorage.getItem('khp-session'),null);});
test('invalid refresh clears session and prevents anonymous writes',async t=>{const original=globalThis.fetch;t.after(()=>globalThis.fetch=original);const client=await auth();let calls=0;globalThis.fetch=async()=>{calls++;return Response.json({message:'invalid refresh'},{status:401});};await assert.rejects(client.rest('hp_staff_documents','','POST',{}),/เข้าสู่ระบบ/);assert.equal(calls,1);assert.equal(client.currentSession(),null);});
test('temporary refresh failure retains recoverable expired session and succeeds on retry',async t=>{const original=globalThis.fetch;t.after(()=>globalThis.fetch=original);const client=await auth();globalThis.fetch=async()=>{throw new TypeError('offline');};await assert.rejects(client.refreshSession(),/offline/);assert.equal(client.currentSession().refresh_token,'test-refresh');globalThis.fetch=async()=>Response.json(token);await client.refreshSession();assert.equal(client.currentSession().access_token,'test-new');});
test('temporary refresh failure can continue using a still-valid access token',async t=>{const original=globalThis.fetch;t.after(()=>globalThis.fetch=original);const client=await auth(Date.now()/1000+30);globalThis.fetch=async()=>{throw new TypeError('offline');};assert.equal((await client.refreshSession()).access_token,'test-old');});
test('logout clears local identity even when logout API is unreachable',async t=>{const original=globalThis.fetch;t.after(()=>globalThis.fetch=original);const client=await auth();globalThis.fetch=async()=>{throw new TypeError('offline');};await assert.rejects(client.logout(),/offline/);assert.equal(client.currentSession(),null);});
test('snapshot outage uses dated HDC cache and recovers on the next request',async t=>{const original=globalThis.fetch;t.after(()=>{globalThis.fetch=original;delete globalThis.window;delete globalThis.localStorage;});globalThis.window={};const data={rows:[{hospcode:'06116',result:4}],fetched_at:'2026-10-01T00:00:00Z',source_date:'2026-09-30'};globalThis.localStorage={getItem:k=>k==='khp-hdc-v1-test-2569'?JSON.stringify(data):null};const {fetchHdc}=await import('../src/api/hdc/client.js?stability=1');globalThis.fetch=async()=>{throw new TypeError('snapshot down');};const stale=await fetchHdc({table:'test'},2569,[]);assert.equal(stale.stale,true);assert.equal(stale.rows[0].result,4);assert.equal(stale.source_date,data.source_date);globalThis.fetch=async()=>Response.json({datasets:{'test|2569':{...data,rows:[{result:5}],fetched_at:'2026-10-07T00:00:00Z'}}});const fresh=await fetchHdc({table:'test'},2569,[]);assert.equal(fresh.rows[0].result,5);assert.equal(fresh.delivery,'scheduled_snapshot');});
