import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {officialMonthlyBody} from '../src/staff/monthly-official.js';
import {officialPayload,renderOfficialFields} from '../src/staff/official-fields.js';
const app=fs.readFileSync(new URL('../src/app.js',import.meta.url),'utf8');
test('delegated document selection is limited to ADMIN or same-unit STAFF',()=>{const code=app.slice(app.indexOf('function canManageStaff('),app.indexOf('async function loadStaffDocuments('));let role='USER',unit='06116';const personnel=[{id:'a',facility_code:'06116'},{id:'b',facility_code:'06117'}];const state={permissions:[],personnelLinks:[],staffPersonId:'a',facilities:[]};const ctx=vm.createContext({state,data:()=>personnel,currentSession:()=>({user:{id:'owner'}}),mustChangePassword:()=>false});vm.runInContext(code,ctx);for(const [permission,selected,expected]of [[{role:'USER',facility_code:'06116'},'a',null],[{role:'STAFF',facility_code:'06117'},'a',null],[{role:'STAFF',facility_code:'06116'},'a','a'],[{role:'ADMIN'},'b','b']]){state.permissions=[permission];state.staffPersonId=selected;assert.equal(vm.runInContext('currentStaffIdentity().person?.id??null',ctx),expected);}});
test('nine histories roundtrip without dropping rows and print in one compact sheet',()=>{const fd=new FormData();for(let i=0;i<9;i++)fd.set('history_'+i+'_facility_name','หน่วยบริการ '+i);const data=officialPayload(fd,'chor11_monthly');assert.equal(JSON.parse(data.service_history).length,9);assert.match(renderOfficialFields('chor11_monthly',data),/history_8_facility_name/);const html=officialMonthlyBody({period_month:'2026-10-01'},{...data,service_as_of:'2026-10-31'});assert.equal((html.match(/class="monthly-history"/g)||[]).length,9);assert.equal((html.match(/class="monthly-sheet monthly-compact"/g)||[]).length,1);assert.match(html,/๑๐\. ปฏิบัติงาน/);});

test('shared monthly rules use 16 pt for up to six or over nine histories and compact 15 pt for seven to nine',()=>{for(const [count,compact,sheets]of [[6,false,1],[7,true,1],[9,true,1],[10,false,2],[12,false,2]]){const html=officialMonthlyBody({period_month:'2026-10-01'},{service_as_of:'2026-10-31',service_history:JSON.stringify(Array.from({length:count},(_,i)=>({facility_name:'หน่วย '+i})))});assert.equal(html.includes('class="monthly-sheet monthly-compact"'),compact);assert.equal((html.match(/<main class="monthly-sheet/g)||[]).length,sheets);assert.equal((html.match(/class="monthly-history"/g)||[]).length,count);assert.match(html,/template class="monthly-continuation"/);}});
