import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';
import {officialAnnualBody,annualLicenseSlots} from '../src/staff/annual-official.js';
import {renderDocumentForm} from '../src/staff/documents.js';
test('annual editor covers applicant print fields and separates manual approval fields',()=>{
 const html=renderDocumentForm('chor11_annual',{person:{full_name:'ทดสอบ',position_name:'นักวิชาการสาธารณสุข'}});
 const fields=['written_at','request_date','level_name','service_years','bureau','unit_moo','unit_subdistrict','unit_district','unit_province','work_date_from','work_date_to','duration_years','duration_months','duration_hours','address_no','road','address_subdistrict','address_district','address_province','postcode','license_type','license_other','no_professional_license','license_number','license_issue_date','monthly_rate','total_amount','amount_in_words'];
 for(const key of fields)assert.equal((html.match(new RegExp('name="'+key+'"','g'))||[]).length,1,key);
 assert.match(html,/ระดับตำแหน่งตามแบบรายปี/);assert.match(html,/ตำแหน่งผู้บริหารให้เติมภายหลัง/);
 assert.doesNotMatch(html,/name="(?:citizen_id|birth_date|approver_name|approver_position)"/);
});
test('annual assets lock the selected source pages and preserve both vector pages',()=>{const source=JSON.parse(fs.readFileSync(new URL('../assets/forms/chor11-annual-source.json',import.meta.url)));assert.deepEqual(source.source_pages,[5,6]);assert.equal(source.source_sha256,'bb3d1b91a83d539e90a9537eed969241accd7d6db64c20493b5f4cbc017ad13d');for(const [file,hash] of Object.entries(source.files)){const raw=fs.readFileSync(new URL('../assets/forms/'+file,import.meta.url));const content=file.endsWith('.svg')?raw.toString('utf8').replace(/\r\n/g,'\n'):raw;assert.equal(createHash('sha256').update(content).digest('hex'),hash,file);}assert.deepEqual(source.page_size_pt,[595.32,841.92]);});
test('annual unknown values stay blank and only confirmed allowance category is selected',()=>{const html=officialAnnualBody({},{});assert.doesNotMatch(html,/data-print-field=|data-license=/);assert.equal((html.match(/data-category=/g)||[]).length,1);assert.match(html,/LUMP_SUM_ALLOWANCE/);});
test('annual overlays both date parts and amounts using stored data without filling review decisions',()=>{const html=officialAnnualBody({},{full_name:'<test>',request_date:'2026-10-10',monthly_rate:2800,total_amount:33600,license_type:'medical_practice'});assert.match(html,/&lt;test&gt;/);assert.match(html,/request_date_day/);assert.match(html,/ตุลาคม/);assert.match(html,/๒๕๖๙/);assert.match(html,/๒,๘๐๐.๐๐/);assert.match(html,/data-license="medical_practice"/);assert.doesNotMatch(html,/data-print-field="(?:review|approver)|<test>/);assert.equal(Object.keys(annualLicenseSlots).length,10);});
test('annual does not convert a legacy engineering license into a medical license',()=>{assert.throws(()=>officialAnnualBody({},{license_type:'engineering'}),/ไม่มีในแบบต้นฉบับ/);assert.throws(()=>officialAnnualBody({},{license_type:'nursing',no_professional_license:1}),/ขัดกัน/);const html=renderDocumentForm('chor11_annual',{person:{full_name:'ทดสอบ'},record:{form_data:{license_type:'engineering'}}});assert.match(html,/value="engineering" selected/);assert.match(html,/ข้อมูลเดิม: ไม่มีตัวเลือก/);});

test('annual converts all data digits to Thai and reserves approver position space',()=>{const data={unit_moo:'3',address_no:'413/2',postcode:'52000',license_number:'AB123'};const before=JSON.stringify(data);const html=officialAnnualBody({},data);for(const value of ['๓','๔๑๓/๒','๕๒๐๐๐','AB๑๒๓'])assert.ok(html.includes('>'+value+'</span>'));assert.match(html,/annual-approver-position/);assert.match(html,/chor11-annual-expanded-2/);assert.equal(JSON.stringify(data),before);});
