import test from 'node:test';
import assert from 'node:assert/strict';
import {documentPayload,renderDocumentForm,renderStaffWorkspace} from '../src/staff/documents.js';
import {officialMonthlyBody} from '../src/staff/monthly-official.js';
import {officialPayload} from '../src/staff/official-fields.js';
const person={full_name:'ชื่อ ที่ไม่ควรแยกเอง',facility_code:'06116'};
function payload(extra={}){const saved=globalThis.FormData;globalThis.FormData=class{get(k){return ({form_code:'chor11_monthly',fiscal_year:2570,period_month:'2026-10-01',...extra})[k]??null;}};try{return documentPayload({}, {person});}finally{globalThis.FormData=saved;}}
test('unknown numbers stay absent; explicit zeros survive and saves remain drafts',()=>{const unknown=payload({work_days:'',leave_days:'',monthly_rate:'',total_amount:''});for(const key of ['work_days','leave_days','monthly_rate','total_amount'])assert.equal(Object.hasOwn(unknown.form_data,key),false);const confirmed=payload({work_days:'0',leave_days:'0',monthly_rate:'2800',total_amount:'0'});assert.equal(confirmed.form_data.work_days,0);assert.equal(confirmed.form_data.total_amount,0);assert.equal(confirmed.status,'draft');});
test('new forms leave request dates, service age and amount blank rather than infer values',()=>{const html=renderDocumentForm('chor11_monthly',{person,record:{form_data:{monthly_rate:2800}}});for(const key of ['request_date','leave_days','total_amount'])assert.match(html,new RegExp('name="'+key+'"[^>]*value=""'));assert.match(html,/name="training_regional_from_date"/);assert.match(html,/name="training_district_to_date"/);assert.match(html,/name="training_years"/);});
test('monthly name blanks require explicit structured names and training needs explicit applicability',()=>{const record={period_month:'2026-10-01'};const html=officialMonthlyBody(record,{full_name:person.full_name,training_regional_selected:1,training_regional_facility:'unverified'});assert.doesNotMatch(html,/data-print-field="first_name"|data-print-field="last_name"|unverified/);const filled=officialMonthlyBody(record,{training_status:2,training_regional_selected:1,training_regional_facility:'<clinic>'});assert.match(filled,/&lt;clinic&gt;/);assert.match(filled,/training_regional_checked/);assert.doesNotMatch(filled,/data-print-field="training_years"/);});
test('cutoff and training ranges reject invalid or guessed inputs',()=>{const fd=v=>({get:k=>v[k]??null});assert.throws(()=>officialPayload(fd({service_as_of:'2026-10-10'}),'chor11_annual'),/สิ้นเดือน/);assert.equal(officialPayload(fd({service_as_of:'2026-10-31'}),'chor11_annual').service_as_of,'2026-10-31');assert.throws(()=>officialPayload(fd({training_status:'3'}),'chor11_monthly'));assert.throws(()=>officialPayload(fd({training_regional_from_date:'2026-10-31',training_regional_to_date:'2026-10-01'}),'chor11_monthly'));});

test('workspace does not present unknown amount as zero baht',()=>{const html=renderStaffWorkspace({person,fiscalYear:2570,documents:[{id:'x',form_code:'chor11_monthly',fiscal_year:2570,period_month:'2026-10-01',form_data:{}}]});assert.match(html,/ยังไม่ระบุ/);assert.doesNotMatch(html,/0\.00 บาท/);});
