import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {officialMonthlyBody} from '../src/staff/monthly-official.js';
import {renderOfficialFields} from '../src/staff/official-fields.js';
import {renderStaffWorkspace} from '../src/staff/documents.js';
const record={period_month:'2026-10-01'};
test('monthly template preserves the exact supplied blank PDF and its vector page',()=>{const digest=file=>createHash('sha256').update(file.endsWith('.svg')?fs.readFileSync(new URL('../assets/forms/'+file,import.meta.url),'utf8').replace(/\r\n/g,'\n'):fs.readFileSync(new URL('../assets/forms/'+file,import.meta.url))).digest('hex');assert.equal(digest('chor11-monthly-official.pdf'),'444625d8dc119b293bb6367ad7b9d1e51c3f221f422d5970f5f6d8ca0f700571');assert.equal(digest('chor11-monthly-official.svg'),'21c6f9dcf94c8bfc74bb5bedc36d63bd22cbfbb3229817099bb89b3c25f24973');});
test('monthly prints separate name fields and the area group, and never silently drops excess history',()=>{const html=officialMonthlyBody(record,{full_name:'นาย ตัวอย่าง ทดสอบ',applicant_first_name:'นาย ตัวอย่าง',applicant_last_name:'ทดสอบ',level_name:'พื้นที่ชุมชนเมือง',service_history:'[]'});assert.match(html,/data-print-field="first_name"[^]*นาย ตัวอย่าง/);assert.match(html,/data-print-field="last_name"[^]*ทดสอบ/);assert.match(html,/data-print-field="area_level"[^]*พื้นที่ชุมชนเมือง/);assert.match(html,/chor11-monthly-official\.svg/);assert.match(html,/chor11-monthly-official\.pdf/);assert.throws(()=>officialMonthlyBody(record,{service_history:JSON.stringify(Array.from({length:7},()=>({})))}),/6 รายการ/);});
test('monthly editor always exposes six original history slots, without fabricated records',()=>{const html=renderOfficialFields('chor11_monthly',{service_history:JSON.stringify([{facility_name:'หน่วยเดิม'}])});assert.match(html,/history_5_facility_name/);assert.doesNotMatch(html,/history_6_facility_name/);assert.equal((html.match(/value="หน่วยเดิม"/g)||[]).length,1);});
test('staff can find existing documents when the shared dashboard defaults to another fiscal year',()=>{const html=renderStaffWorkspace({documents:[{...record,id:'m1',form_code:'chor11_monthly',fiscal_year:2570}],person:{full_name:'ทดสอบ'},fiscalYear:2569});assert.match(html,/data-staff-year="2570"/);assert.match(html,/ข้อมูลที่บันทึกไว้ของคุณอยู่ในปี/);});

test('monthly converts digits inside text fields without changing stored data',()=>{const data={level_name:'ปกติ 2',service_as_of:'2026-10-31',service_history:JSON.stringify([{facility_name:'หน่วย 12',level_name:'ปกติ 2'}])};const before=JSON.stringify(data);const html=officialMonthlyBody(record,data);assert.match(html,/ปกติ ๒/);assert.match(html,/หน่วย ๑๒/);assert.doesNotMatch(html,/>[^<]*[0-9][^<]*</);assert.equal(JSON.stringify(data),before);});

test('monthly legacy spacing keeps six history rows and dotted fields at 16 pt',async()=>{const {monthlyLayoutCSS}=await import('../src/staff/monthly-layout.js');const html=officialMonthlyBody(record,{});assert.equal((html.match(/class="monthly-history"/g)||[]).length,6);assert.match(monthlyLayoutCSS,/font-size:16pt/);assert.match(monthlyLayoutCSS,/border-bottom:1px dotted/);assert.match(monthlyLayoutCSS,/padding:10mm 16mm 12mm/);assert.doesNotMatch(html,/class="official-background"/);});

test('monthly uses full unit names in spacious fields and history without overwriting data',()=>{const data={facility_name:'ศบส.บ้านโทกหัวช้าง',service_as_of:'2026-10-31',history_print_names:'["ชื่อย่อ"]',service_history:JSON.stringify([{facility_name:'ศูนย์บริการสาธารณสุขบ้านโทกหัวช้าง'}])};const before=JSON.stringify(data);const html=officialMonthlyBody(record,data);assert.equal((html.match(/ศูนย์บริการสาธารณสุขบ้านโทกหัวช้าง/g)||[]).length,3);assert.doesNotMatch(html,/ชื่อย่อ|ศบส\./);assert.equal(JSON.stringify(data),before);});
