import test from 'node:test';
import assert from 'node:assert/strict';
import {printableDocument,printableCertificate,renderStaffWorkspace} from '../src/staff/documents.js';
import {officialPayload,renderOfficialFields} from '../src/staff/official-fields.js';
const monthly={id:'m1',form_code:'chor11_monthly',period_month:'2026-10-01',fiscal_year:2570,form_data:{full_name:'ตัวอย่าง',position_name:'พยาบาล',facility_name:'หน่วยทดสอบ',work_days:20,leave_days:1,calendar_work_days:21}};
test('annual uses the selected two-page vector originals and leaves official decisions blank',()=>{const html=printableDocument({form_code:'chor11_annual',form_data:{}});assert.equal((html.match(/class="official-background"/g)||[]).length,2);assert.match(html,/chor11-annual-official-1\.svg/);assert.match(html,/chor11-annual-expanded-2\.svg/);assert.doesNotMatch(html,/data-print-field="(?:review|approver)|2566|๒๕๖๖|นายกเทศมนตรีเมืองเขลางค์นคร/);});

test('monthly retains training and service history with calendar year, excluding the former summary table',()=>{const html=printableDocument({...monthly,form_data:{...monthly.form_data,service_as_of:'2026-10-31',service_history:JSON.stringify([{facility_name:'สถานที่เดิม <script>',province:'ลำปาง',start_date:'2010-01-01',end_date:'2011-01-01',duration_years:1}])}});assert.match(html,/ฝึกเพิ่มพูนทักษะ/);assert.match(html,/สถานที่เดิม &lt;script&gt;/);assert.match(html,/๒๕๖๙/);assert.doesNotMatch(html,/<table>|ข้อมูลการปฏิบัติงานและจำนวนเงินที่ขอรับ|<script>/);});
test('certificate is landscape with nine columns and never asserts attendance before explicit verification',()=>{const draft=printableCertificate(monthly);assert.match(draft,/@page\{size:A4 landscape/);assert.equal((draft.match(/<col style/g)||[]).length,9);assert.match(draft,/ยังไม่ได้ยืนยัน/);assert.doesNotMatch(draft,/class="result-check">✓/);const verified=printableCertificate({...monthly,form_data:{...monthly.form_data,certificate_verified:1}});assert.match(verified,/<td class="result-check">✓<\/td><td class="result-check"><\/td>/);assert.doesNotMatch(verified,/<script>|onclick=/);});
test('certificate action derives from a monthly record without a third document or table',()=>{const html=renderStaffWorkspace({documents:[monthly],person:{full_name:'ทดสอบ'},fiscalYear:2570});assert.match(html,/data-staff-certificate="m1"/);assert.throws(()=>printableCertificate({form_code:'chor11_annual'}));});
test('official editor preserves imported history in normal fields and rejects missing certificate day data',()=>{const html=renderOfficialFields('chor11_monthly',{service_history:JSON.stringify([{facility_name:'หน่วยเดิม',start_date:'2010-01-01'}])});assert.match(html,/name="history_0_facility_name"[^>]*value="หน่วยเดิม"/);assert.doesNotMatch(html,/JSON|<textarea/);const fd=new FormData();fd.set('history_0_facility_name','หน่วยเดิม');fd.set('history_0_duration_years','2');assert.deepEqual(JSON.parse(officialPayload(fd,'chor11_monthly').service_history),[{facility_name:'หน่วยเดิม',duration_years:2}]);fd.set('certificate_verified','1');assert.throws(()=>officialPayload(fd,'chor11_monthly'),/ตรวจวันทำการ/);});
