import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {documentPayload,printableDocument,renderStaffWorkspace,renderDocumentForm} from '../src/staff/documents.js';
const person={full_name:'ตัวอย่าง',position_name:'พยาบาล',id:'p',facility_code:'06116'};
function payload(values){const old=globalThis.FormData;globalThis.FormData=class{get(k){return values[k]??null;}};try{return documentPayload({}, {person});}finally{globalThis.FormData=old;}}
test('payload enforces active templates, fixed version and fiscal month boundaries',()=>{const v={form_code:'chor11_monthly',template_version:'evil',fiscal_year:'2569',period_month:'2025-10-01',request_date:'2026-01-01',monthly_rate:'2000',total_amount:'2000'};assert.equal(payload(v).template_version,'2569.1');assert.throws(()=>payload({...v,period_month:'2026-10-01'}));assert.throws(()=>payload({...v,period_month:'2025-13-01'}));assert.throws(()=>payload({...v,form_code:'leave_sick'}));assert.throws(()=>payload({...v,total_amount:'-1'}));assert.throws(()=>payload({...v,monthly_rate:'NaN'}));});
test('payload allows only selected fields and takes identity from master',()=>{const r=payload({form_code:'chor11_annual',fiscal_year:2569,monthly_rate:2000,citizen_id:'secret',birth_date:'secret',full_name:'forged'});assert.equal(r.form_data.full_name,person.full_name);assert.equal(r.form_data.citizen_id,undefined);assert.equal(r.form_data.birth_date,undefined);assert.equal(r.form_data.compensation_category,'LUMP_SUM_ALLOWANCE');});
test('monthly list follows selected fiscal year and offers no purge',()=>{const html=renderStaffWorkspace({person,fiscalYear:2569,documents:[{id:'old',form_code:'chor11_monthly',fiscal_year:2568,period_month:'2025-09-01'},{id:'current',form_code:'chor11_monthly',fiscal_year:2569,period_month:'2025-10-01'}]});assert.match(html,/data-staff-edit="current"/);assert.doesNotMatch(html,/data-staff-edit="old"|data-staff-purge/);assert.match(html,/ค่าตอบแทนและสิทธิประโยชน์/);assert.match(html,/การลา/);});
test('annual print has two A4 sheets, unselected approval controls, escaped text and version',()=>{const html=printableDocument({form_code:'chor11_annual',fiscal_year:2569,form_data:{full_name:'<script>bad</script>',monthly_rate:2000}});assert.equal((html.match(/<article class="sheet annual">/g)||[]).length,2);assert.match(html,/@page\{size:A4/);assert.match(html,/ผู้มีอำนาจอนุมัติ/);assert.match(html,/□ อนุมัติ/);assert.doesNotMatch(html,/<script>|onclick\s*=/i);assert.match(html,/แบบพิมพ์รุ่น 2569.1/);});
test('print refreshes identity from linked personnel without copying extra attributes',()=>{const html=printableDocument({form_code:'chor11_monthly',period_month:'2026-09-01',form_data:{full_name:'stale'}},{person:{...person,citizen_id:'sensitive'}});assert.match(html,/ตัวอย่าง/);assert.doesNotMatch(html,/stale|sensitive/);assert.match(html,/แบบพิมพ์รุ่น 2569.1/);});
test('record editing retains original fiscal year',()=>{assert.match(renderDocumentForm('chor11_annual',{person,fiscalYear:2570,record:{fiscal_year:2569}}),/name="fiscal_year" value="2569"/);});
test('migration confines deletion and immutable fields with no new persistent tables',()=>{const sql=fs.readFileSync(new URL('../supabase/migrations/20261007_staff_documents_hardening.sql',import.meta.url),'utf8');assert.match(sql,/for delete to authenticated using \(\(select auth.uid\(\)\)=owner_user_id and form_code='chor11_annual'\)/);assert.doesNotMatch(sql,/create table|user_metadata|service_role/i);for(const key of ['owner_user_id','personnel_id','facility_code','form_code'])assert.ok(sql.includes('new.'+key+' is distinct from old.'+key));});
