import {escapeHtml as e} from '../utils/core.js';
import {rest} from '../api/supabase/client.js';
let ctx;
export function parseUnitHash(hash,facilities){const [route,code,tab]=hash.replace(/^#/,'').split('/');if(route!=='unit'||!facilities.some(f=>f.active&&f.facility_code===code))return null;return {code,tab:['home','services','team','performance','resources','contact','manage'].includes(tab)?tab:'home'};}
export function publicInfo(row){return row?.published?row:null;}
export function serviceLines(value){return String(value).split('\n').filter(s=>s.trim()).map(line=>{const [name,schedule='',preparation='']=line.split('|').map(s=>s.trim());if(!name||name.length>200||schedule.length>1000||preparation.length>1000)throw new Error('ตรวจความยาวชื่อบริการ วันเวลา และเอกสาร');return {name,schedule,preparation};});}
export function unitsView(c){ctx=c;const f=c.units().find(f=>f.facility_code===c.code());if(!f)return `<section class="panel"><h2>หน่วยบริการ</h2><p>เลือกหน่วยเพื่อดูบริการ บุคลากร ผลงาน และติดต่อ</p><div class="unit-directory">${c.units().filter(f=>f.active).map(f=>`<a class="panel unit-card" href="#unit/${f.facility_code}/home"><img src="assets/municipality-logo.png" alt=""><div><h2>${e(f.facility_name)}</h2><p class="subtle">รหัส ${f.facility_code} · ${f.area_unit?'มีพื้นที่รับผิดชอบ':'หน่วยบริการ ไม่มีพื้นที่ประชากรรับผิดชอบ'}</p><span>เปิดข้อมูลหน่วย →</span></div></a>`).join('')}</div></section>`;
const row=c.rows().find(r=>r.facility_code===f.facility_code),info=publicInfo(row),tab=c.tab();const tabs=[['home','หน้าแรก'],['services','บริการและข้อมูลประชาชน'],['team','บุคลากร'],['performance','ผลงาน'],['resources','ข้อมูลหน่วยและทรัพยากร'],['contact','ติดต่อ']];if(c.canEdit(f.facility_code))tabs.push(['manage','จัดการข้อมูลหน่วย']);const panel=(title,body)=>`<section class="panel"><h2>${e(title)}</h2>${body}</section>`;
const contact=()=>panel('ติดต่อและเวลาทำการ',info&&(info.address||info.phone||info.opening_hours||info.directions_url)?`${info.address?`<p>ที่อยู่: ${e(info.address)}</p>`:''}${info.phone?`<p>โทรศัพท์หน่วย: ${e(info.phone)}</p>`:''}${info.opening_hours?`<p class="unit-text">เวลาทำการ: ${e(info.opening_hours)}</p>`:''}${/^https:\/\//.test(info.directions_url??'')?`<p><a href="${e(info.directions_url)}" target="_blank" rel="noopener">แผนที่ / การเดินทาง →</a></p>`:''}<p class="subtle">หน่วยตรวจข้อมูลล่าสุด: ${e(new Date(info.reviewed_at??info.updated_at).toLocaleDateString('th-TH'))}</p>`:'<div class="empty">ยังไม่มีข้อมูลติดต่อที่ยืนยันและเผยแพร่</div>');
const services=()=>panel('บริการและข้อมูลสำหรับประชาชน',info?.services?.length?`<div class="unit-directory">${info.services.filter(s=>s.name).map(s=>`<article class="panel"><h2>${e(s.name)}</h2>${s.schedule?`<p class="unit-text">วันเวลา: ${e(s.schedule)}</p>`:''}${s.preparation?`<p class="unit-text">ขั้นตอน / เอกสาร / วิธีเตรียมตัว: ${e(s.preparation)}</p>`:''}</article>`).join('')}</div>`:'<div class="empty">ยังไม่มีบริการที่ยืนยันและเผยแพร่</div>');let body='';
if(tab==='home')body=panel(f.facility_name,`<p>บริการ บุคลากร และผลการดำเนินงานของหน่วย</p><div class="profile-tabs">${tabs.filter(t=>['services','team','performance','contact'].includes(t[0])).map(([v,n])=>`<a class="unit-link" href="#unit/${f.facility_code}/${v}">${n}</a>`).join('')}</div>`)+(info?.services?.length?services():'')+(info&&(info.address||info.phone||info.opening_hours)?contact():'');
if(tab==='services')body=services();if(tab==='contact')body=contact();if(tab==='team')body=c.team(f.facility_code);if(tab==='performance')body=c.performance();if(tab==='resources')body=c.resources();
if(tab==='manage'){if(!c.canEdit(f.facility_code))body=panel('จัดการข้อมูลหน่วย','<div class="empty">ไม่มีสิทธิ์จัดการหน่วยนี้</div>');else body=panel('บริการและข้อมูลสำหรับประชาชน',`<p class="subtle">เจ้าหน้าที่บันทึกร่างเฉพาะหน่วยของตน ADMIN ตรวจและเลือกเผยแพร่ก่อนแสดงให้ประชาชน</p><form id="unit-info-form" data-code="${f.facility_code}" data-existing="${!!row}"><div class="form-grid"><label>ที่อยู่หน่วย<textarea name="address" maxlength="1000">${e(row?.address??'')}</textarea></label><label>โทรศัพท์หน่วย<input name="phone" maxlength="100" value="${e(row?.phone??'')}"></label><label>เวลาทำการ / วันหยุด<textarea name="opening_hours" maxlength="1000">${e(row?.opening_hours??'')}</textarea></label><label>ลิงก์แผนที่ (https)<input name="directions_url" type="url" value="${e(row?.directions_url??'')}"></label></div><label>บริการ — หนึ่งบริการต่อบรรทัด: ชื่อบริการ | วันเวลา | ขั้นตอนหรือเอกสาร<textarea name="service_lines" rows="8" maxlength="20000">${e((row?.services??[]).map(s=>[s.name,s.schedule,s.preparation].join(' | ')).join('\n'))}</textarea></label>${c.admin()?`<label>สถานะ<select name="published"><option value="false" ${!row?.published?'selected':''}>ร่าง / พักการแสดงผล</option><option value="true" ${row?.published?'selected':''}>ยืนยันและเผยแพร่</option></select></label>`:'<input type="hidden" name="published" value="false"><p class="subtle">เมื่อแก้ไขจะเป็นร่าง รอ ADMIN ตรวจและเผยแพร่อีกครั้ง</p>'}<div id="unit-info-error" class="form-error" role="status"></div><button type="submit" class="primary">บันทึกข้อมูลหน่วย</button></form>`);}
return `<section class="panel"><div class="link-row"><a href="#units">← ทุกหน่วยบริการ</a><span>รหัส ${e(f.facility_code)}</span></div><h2>${e(f.facility_name)}</h2><div class="profile-tabs unit-tabs">${tabs.map(([v,n])=>`<a class="unit-link ${v===tab?'active':''}" ${v===tab?'aria-current="page"':''} href="#unit/${f.facility_code}/${v}">${n}</a>`).join('')}</div></section>${body}`;
}
document.addEventListener('submit',async event=>{const form=event.target;if(form.id!=='unit-info-form')return;event.preventDefault();const button=form.querySelector('button[type=submit]');button.disabled=true;try{const values=Object.fromEntries(new FormData(form));values.services=serviceLines(values.service_lines);delete values.service_lines;if(values.services.length>20)throw new Error('ไม่เกิน 20 บริการต่อหน่วย');values.published=values.published==='true';if(values.directions_url&&new URL(values.directions_url).protocol!=='https:')throw new Error('ลิงก์แผนที่ต้องเป็น https');await rest('hp_unit_public_info',form.dataset.existing==='true'?'facility_code=eq.'+form.dataset.code:'',form.dataset.existing==='true'?'PATCH':'POST',{...values,facility_code:form.dataset.code});await ctx.reload();const feedback=document.getElementById('unit-info-error');if(feedback)feedback.textContent='บันทึกแล้ว'+(values.published?' และเผยแพร่':' เป็นร่างรอ ADMIN ตรวจ');}catch(error){document.getElementById('unit-info-error').textContent=error.message;}finally{button.disabled=false;}});
