import {isMedicalDoctor,withoutNonDoctorTraining} from './medical-training.js';
// Scalar additions use the existing private form_data column, not extra tables.
export const officialFields={
 common:{applicant_first_name:'คำนำหน้าและชื่อ (ตามทะเบียน ไม่แยกจากชื่อเต็มอัตโนมัติ)',applicant_last_name:'นามสกุล',service_as_of:'วันที่ใช้นับอายุงาน (วันสิ้นเดือน)',bureau:'สังกัดสำนัก/กอง',unit_moo:'หน่วยบริการ: หมู่ที่',unit_subdistrict:'หน่วยบริการ: ตำบล',unit_district:'หน่วยบริการ: อำเภอ',unit_province:'หน่วยบริการ: จังหวัด',level_name:'ระดับ/กลุ่มพื้นที่ตามแบบคำขอ (ตรวจตามสิทธิ ไม่ใช่ระดับตำแหน่ง)',service_years:'อายุงานรวม (ปี)',service_months:'อายุงานรวม (เดือน)',service_days:'อายุงานรวม (วัน)'},
 annual:{address_no:'ที่อยู่: บ้านเลขที่',road:'ที่อยู่: ถนน',address_subdistrict:'ที่อยู่: ตำบล/แขวง',address_district:'ที่อยู่: อำเภอ/เขต',address_province:'ที่อยู่: จังหวัด',postcode:'รหัสไปรษณีย์',license_other:'ใบอนุญาตอื่น ระบุ',license_issue_date:'วันที่ออกใบอนุญาต',no_professional_license:'ไม่มีใบอนุญาต (0=ยังไม่เลือก, 1=ไม่มี)',duration_years:'ระยะเวลาที่ขอรับ (ปี)',duration_months:'ระยะเวลาที่ขอรับ (เดือน)',duration_hours:'ระยะเวลาที่ขอรับ (ชั่วโมง)',total_amount:'รวมเงินที่ขอรับทั้งช่วง (บาท)',amount_in_words:'จำนวนเงินเป็นตัวอักษร'},
 monthly:{training_status:'การฝึกเพิ่มพูนทักษะ',training_years:'ฝึกเพิ่มพูนทักษะ: รวมปี',training_months:'ฝึกเพิ่มพูนทักษะ: รวมเดือน',training_regional_selected:'รพศ./รพท.: เลือกประวัติฝึก',training_regional_facility:'รพศ./รพท.: ชื่อโรงพยาบาล',training_regional_province:'รพศ./รพท.: จังหวัด',training_regional_from_date:'รพศ./รพท.: ตั้งแต่วันที่',training_regional_to_date:'รพศ./รพท.: ถึงวันที่',training_district_selected:'รพช.: เลือกประวัติฝึก',training_district_facility:'รพช.: ชื่อโรงพยาบาล',training_district_province:'รพช.: จังหวัด',training_district_from_date:'รพช.: ตั้งแต่วันที่',training_district_to_date:'รพช.: ถึงวันที่',service_history:'ประวัติการปฏิบัติงาน',calendar_work_days:'วันทำการของเดือนตามปฏิทิน',certificate_verified:'ยืนยันวันทำงานและวันลาแล้ว (0=ยัง, 1=ยืนยัน)',head_name:'ชื่อหัวหน้าหน่วยผู้ลงนาม',head_position:'ตำแหน่งหัวหน้าหน่วย',director_name:'ชื่อผู้อำนวยการกองผู้ลงนาม',director_position:'ตำแหน่งผู้อำนวยการกอง'}
};
export const officialNumbers=new Set(['training_status','training_years','training_months','training_regional_selected','training_district_selected','service_years','service_months','service_days','no_professional_license','duration_years','duration_months','duration_hours','total_amount','calendar_work_days','certificate_verified']);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function historyEditor(value,printValue){let printNames=[];try{printNames=JSON.parse(printValue||'[]');}catch{}let rows=[];try{rows=JSON.parse(value||'[]');}catch{}if(!Array.isArray(rows))rows=[];const labels={facility_name:'หน่วยบริการ',province:'จังหวัด',level_name:'ระดับ/กลุ่ม',start_date:'เริ่มวันที่',end_date:'ถึงวันที่',duration_years:'รวมปี',duration_months:'เดือน',duration_days:'วัน'};return '<fieldset style="grid-column:1/-1"><legend>ประวัติการปฏิบัติงาน</legend>'+Array.from({length:Math.min(12,Math.max(6,rows.length+1))},(_,i)=>'<fieldset><legend>รายการที่ '+(i+1)+'</legend><div class="form-grid">'+Object.entries(labels).map(([key,label])=>'<label>'+label+'<input name="history_'+i+'_'+key+'" '+(key.endsWith('_date')?'type="date"':key.startsWith('duration_')?'type="number" min="0" step="1"':'maxlength="150"')+' value="'+esc(rows[i]?.[key]??'')+'"></label>').join('')+'<label>ชื่อสำหรับพิมพ์ในช่องแคบ (ไม่เกิน 60 ตัวอักษร; เว้นว่างใช้ชื่อเต็ม)<input name="history_'+i+'_print_name" maxlength="60" value="'+esc(printNames[i]??'')+'"></label></div></fieldset>').join('')+'</fieldset>';}
function renderFields(code,f){const fields={...officialFields.common,...officialFields[code==='chor11_annual'?'annual':'monthly']};if(code==='chor11_annual')for(const k of ['service_years','service_months','service_days'])delete fields[k];return '<fieldset><legend>รายละเอียดตามแบบพิมพ์ต้นฉบับ</legend><p class="subtle">บันทึกเป็นฉบับร่าง ช่องที่ไม่ทราบให้เว้นไว้ ไม่ถือเป็นศูนย์ • ช่องที่มีรายการแนะนำเลือกได้ หรือพิมพ์ค่าอื่นเอง • อัตราและจำนวนเงินใช้ในทะเบียนเบิก ส่วนวันทำงานและผู้ลงนามใช้ในใบรับรอง • แบบรายเดือนใช้ PDF ต้นฉบับเดิม ข้อฝึกเพิ่มพูนทักษะส่วนรวมปี/เดือนในต้นฉบับไม่มีช่องว่างเพียงพอ จึงเก็บข้อมูลไว้แต่ยังไม่พิมพ์ทับข้อความ ต้องยืนยันต้นฉบับก่อน • แบบประจำปีใช้หน้า 5–6 ของระเบียบ พ.ศ.2562 ตามผู้ใช้กำหนด ส่วนใบรับรองยังรอตรวจเทียบ PDF ต้นฉบับ</p><div class="form-grid">'+Object.entries(fields).map(([key,label])=>key==='service_history'?historyEditor(f[key],f.history_print_names):key==='training_status'?'<label>'+label+'<select name="training_status">'+['ยังไม่ยืนยัน','ไม่เกี่ยวข้อง','เกี่ยวข้อง'].map((text,i)=>'<option value="'+i+'" '+(Number(f[key]||0)===i?'selected':'')+'>'+text+'</option>').join('')+'</select></label>':['certificate_verified','no_professional_license','training_regional_selected','training_district_selected'].includes(key)?'<label>'+label+'<select name="'+key+'"><option value="0" '+(Number(f[key]||0)===0?'selected':'')+'>'+(key==='certificate_verified'?'ยังไม่ยืนยัน':'ยังไม่เลือก')+'</option><option value="1" '+(Number(f[key])===1?'selected':'')+'>'+(key==='certificate_verified'?'ตรวจสอบและยืนยันแล้ว':key==='no_professional_license'?'ไม่มีใบอนุญาต':'เลือก')+'</option></select></label>':'<label>'+label+'<input name="'+key+'" '+(officialNumbers.has(key)?'type="number" min="0" step="0.01"':(key==='license_issue_date'||key==='service_as_of'||key.endsWith('_date'))?'type="date"':'maxlength="200"')+' value="'+esc(f[key]??'')+'"></label>').join('')+'</div></fieldset>';}
function parseOfficialPayload(fd,code){const out={};for(const key of Object.keys({...officialFields.common,...officialFields[code==='chor11_annual'?'annual':'monthly']})){const value=fd.get(key);if(key==='service_history'){const rows=[];const names=[];for(let i=0;i<12;i++){const row={};for(const field of ['facility_name','province','level_name','start_date','end_date','duration_years','duration_months','duration_days']){const raw=String(fd.get('history_'+i+'_'+field)||'').trim();if(raw)row[field]=field.startsWith('duration_')?Number(raw):raw;}const name=String(fd.get('history_'+i+'_print_name')||'').trim();if(name.length>60)throw new Error('ชื่อที่ใช้พิมพ์ยาวเกิน 60 ตัวอักษร');if(name&&!Object.keys(row).length)throw new Error('กรอกประวัติหน่วยบริการก่อนกำหนดชื่อพิมพ์');if(Object.keys(row).length){rows.push(row);names.push(name);}}out[key]=JSON.stringify(rows);if(names.some(Boolean))out.history_print_names=JSON.stringify(names);continue;}if(value===null)continue;if(officialNumbers.has(key)){if(value==='')continue;const n=Number(value);if(!Number.isFinite(n)||n<0)throw new Error('ตัวเลขต้องไม่ติดลบ');out[key]=n;}else out[key]=String(value).trim();}for(const key of ['training_status','training_regional_selected','training_district_selected'])if(out[key]!=null&&(!Number.isInteger(out[key])||out[key]>(key==='training_status'?2:1)))throw new Error('สถานะการฝึกเพิ่มพูนทักษะไม่ถูกต้อง');if(out.service_as_of){const cutoff=new Date(out.service_as_of+'T00:00:00Z');if(Number.isNaN(cutoff.getTime())||cutoff.toISOString().slice(0,10)!==out.service_as_of||new Date(cutoff.getTime()+86400000).getUTCDate()!==1)throw new Error('วันที่นับอายุงานต้องเป็นวันสิ้นเดือน');}if(out.training_months>11)throw new Error('เดือนฝึกเพิ่มพูนทักษะต้องไม่เกิน 11');for(const kind of ['regional','district'])if(out['training_'+kind+'_from_date']&&out['training_'+kind+'_to_date']&&out['training_'+kind+'_from_date']>out['training_'+kind+'_to_date'])throw new Error('ช่วงฝึกเพิ่มพูนทักษะไม่ถูกต้อง');if(out.service_history){let rows;try{rows=JSON.parse(out.service_history);}catch{throw new Error('รูปแบบประวัติงานไม่ถูกต้อง');}if(!Array.isArray(rows)||rows.length>12||rows.some(r=>!r||typeof r!=='object'||Array.isArray(r)||Object.keys(r).some(k=>!['facility_name','province','level_name','start_date','end_date','duration_years','duration_months','duration_days'].includes(k))))throw new Error('รูปแบบประวัติงานไม่ถูกต้อง');if(out.service_history.length>10000)throw new Error('ประวัติงานยาวเกิน 10,000 ตัวอักษร');}if(code==='chor11_monthly'&&out.certificate_verified===1){const work=fd.get('work_days'),leave=fd.get('leave_days');if(out.calendar_work_days==null||work==null||leave==null||work===''||leave===''||Number(work)+Number(leave)>out.calendar_work_days)throw new Error('ตรวจวันทำการ วันปฏิบัติงาน และวันลาก่อนยืนยันใบรับรอง');}return out;}

export function renderOfficialFields(code,f,{person}={}){
 if(code!=='chor11_monthly'||!person||isMedicalDoctor(person.position_name))return renderFields(code,f);
 const message='<p id="doctor-training-notice" class="notice">ข้อ ๑ การฝึกเพิ่มพูนทักษะ สำหรับตำแหน่งแพทย์เท่านั้น ตำแหน่งของท่านไม่ต้องกรอก ระบบล็อกช่องส่วนนี้ไว้ ส่วนประวัติการปฏิบัติงานและข้อมูลอื่นกรอกได้ตามปกติ</p>';
 const html=renderFields(code,withoutNonDoctorTraining(f,person.position_name));
 return message+html.replace(/<(?:input|select)\b[^>]*\bname="training_[^"]+"[^>]*>/g,tag=>tag.slice(0,-1)+' disabled aria-describedby="doctor-training-notice">');
}
export function officialPayload(fd,code,{person}={}){
 if(code!=='chor11_monthly'||!person||isMedicalDoctor(person.position_name))return parseOfficialPayload(fd,code);
 const details=parseOfficialPayload({get:key=>key.startsWith('training_')?null:fd.get(key)},code);
 return withoutNonDoctorTraining(details,person.position_name);
}

