// Scalar additions use the existing private form_data column, not extra tables.
export const officialFields={
 common:{bureau:'สังกัดสำนัก/กอง',unit_moo:'หน่วยบริการ: หมู่ที่',unit_subdistrict:'หน่วยบริการ: ตำบล',unit_district:'หน่วยบริการ: อำเภอ',unit_province:'หน่วยบริการ: จังหวัด',level_name:'ระดับ/กลุ่มตามแบบคำขอ',service_years:'อายุงานรวม (ปี)',service_months:'อายุงานรวม (เดือน)',service_days:'อายุงานรวม (วัน)'},
 annual:{address_no:'ที่อยู่: บ้านเลขที่',road:'ที่อยู่: ถนน',address_subdistrict:'ที่อยู่: ตำบล/แขวง',address_district:'ที่อยู่: อำเภอ/เขต',address_province:'ที่อยู่: จังหวัด',postcode:'รหัสไปรษณีย์',license_other:'ใบอนุญาตอื่น ระบุ',license_issue_date:'วันที่ออกใบอนุญาต',no_professional_license:'ไม่มีใบอนุญาต (0=ยังไม่เลือก, 1=ไม่มี)',duration_years:'ระยะเวลาที่ขอรับ (ปี)',duration_months:'ระยะเวลาที่ขอรับ (เดือน)',duration_hours:'ระยะเวลาที่ขอรับ (ชั่วโมง)',total_amount:'รวมเงินที่ขอรับทั้งช่วง (บาท)',amount_in_words:'จำนวนเงินเป็นตัวอักษร'},
 monthly:{service_history:'ประวัติการปฏิบัติงาน',calendar_work_days:'วันทำการของเดือนตามปฏิทิน',certificate_verified:'ยืนยันวันทำงานและวันลาแล้ว (0=ยัง, 1=ยืนยัน)',head_name:'ชื่อหัวหน้าหน่วยผู้ลงนาม',head_position:'ตำแหน่งหัวหน้าหน่วย',director_name:'ชื่อผู้อำนวยการกองผู้ลงนาม',director_position:'ตำแหน่งผู้อำนวยการกอง'}
};
export const officialNumbers=new Set(['service_years','service_months','service_days','no_professional_license','duration_years','duration_months','duration_hours','total_amount','calendar_work_days','certificate_verified']);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function historyEditor(value){let rows=[];try{rows=JSON.parse(value||'[]');}catch{}if(!Array.isArray(rows))rows=[];const labels={facility_name:'หน่วยบริการ',province:'จังหวัด',level_name:'ระดับ/กลุ่ม',start_date:'เริ่มวันที่',end_date:'ถึงวันที่',duration_years:'รวมปี',duration_months:'เดือน',duration_days:'วัน'};return '<fieldset style="grid-column:1/-1"><legend>ประวัติการปฏิบัติงาน</legend>'+Array.from({length:Math.min(12,Math.max(4,rows.length+1))},(_,i)=>'<fieldset><legend>รายการที่ '+(i+1)+'</legend><div class="form-grid">'+Object.entries(labels).map(([key,label])=>'<label>'+label+'<input name="history_'+i+'_'+key+'" '+(key.endsWith('_date')?'type="date"':key.startsWith('duration_')?'type="number" min="0" step="1"':'maxlength="150"')+' value="'+esc(rows[i]?.[key]??'')+'"></label>').join('')+'</div></fieldset>').join('')+'</fieldset>';}
export function renderOfficialFields(code,f){const fields={...officialFields.common,...officialFields[code==='chor11_annual'?'annual':'monthly']};if(code==='chor11_annual')for(const k of ['service_years','service_months','service_days'])delete fields[k];return '<fieldset><legend>รายละเอียดตามแบบพิมพ์ต้นฉบับ</legend><p class="subtle">ตรวจข้อมูลก่อนลงนาม ช่องที่ยังไม่ยืนยันให้เว้นไว้ ใบรับรองพิมพ์เฉพาะเจ้าของรายการนี้</p><div class="form-grid">'+Object.entries(fields).map(([key,label])=>key==='service_history'?historyEditor(f[key]):['certificate_verified','no_professional_license'].includes(key)?'<label>'+label+'<select name="'+key+'"><option value="0" '+(Number(f[key]||0)===0?'selected':'')+'>'+(key==='certificate_verified'?'ยังไม่ยืนยัน':'ยังไม่เลือก')+'</option><option value="1" '+(Number(f[key])===1?'selected':'')+'>'+(key==='certificate_verified'?'ตรวจสอบและยืนยันแล้ว':'ไม่มีใบอนุญาต')+'</option></select></label>':'<label>'+label+'<input name="'+key+'" '+(officialNumbers.has(key)?'type="number" min="0" step="0.01"':key==='license_issue_date'?'type="date"':'maxlength="200"')+' value="'+esc(f[key]??'')+'"></label>').join('')+'</div></fieldset>';}
export function officialPayload(fd,code){const out={};for(const key of Object.keys({...officialFields.common,...officialFields[code==='chor11_annual'?'annual':'monthly']})){const value=fd.get(key);if(key==='service_history'){const rows=[];for(let i=0;i<12;i++){const row={};for(const field of ['facility_name','province','level_name','start_date','end_date','duration_years','duration_months','duration_days']){const raw=String(fd.get('history_'+i+'_'+field)||'').trim();if(raw)row[field]=field.startsWith('duration_')?Number(raw):raw;}if(Object.keys(row).length)rows.push(row);}out[key]=JSON.stringify(rows);continue;}if(value===null)continue;if(officialNumbers.has(key)){if(value==='')continue;const n=Number(value);if(!Number.isFinite(n)||n<0)throw new Error('ตัวเลขต้องไม่ติดลบ');out[key]=n;}else out[key]=String(value).trim();}if(out.service_history){let rows;try{rows=JSON.parse(out.service_history);}catch{throw new Error('รูปแบบประวัติงานไม่ถูกต้อง');}if(!Array.isArray(rows)||rows.length>12||rows.some(r=>!r||typeof r!=='object'||Array.isArray(r)||Object.keys(r).some(k=>!['facility_name','province','level_name','start_date','end_date','duration_years','duration_months','duration_days'].includes(k))))throw new Error('รูปแบบประวัติงานไม่ถูกต้อง');if(out.service_history.length>1000)throw new Error('ประวัติงานยาวเกิน 1,000 ตัวอักษร');}if(code==='chor11_monthly'&&out.certificate_verified===1){const work=fd.get('work_days'),leave=fd.get('leave_days');if(out.calendar_work_days==null||work===''||leave===''||Number(work)+Number(leave)>out.calendar_work_days)throw new Error('ตรวจวันทำการ วันปฏิบัติงาน และวันลาก่อนยืนยันใบรับรอง');}return out;}
