const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?new Date(v+'T00:00:00').toLocaleDateString('th-TH',{day:'numeric',month:'long',year:'numeric'}):'................................';
const money=v=>Number(v??0).toLocaleString('th-TH',{minimumFractionDigits:2,maximumFractionDigits:2});
const fill=v=>'<span class="fill">'+esc(v||'................................')+'</span>';
const signature=(f,role='ผู้ยื่นคำขอ')=>'<div class="signature">ลงชื่อ ........................................................ '+role+'<br>('+esc(f.full_name)+')<br>'+esc(f.position_name)+' '+esc(f.position_level)+'</div>';
const footer=(page)=>'<footer>แบบพิมพ์รุ่น 2569.1 • หน้า '+page+' • Design & Developed by Apiwat Meethong</footer>';
const certification='ข้าพเจ้าขอรับรองว่าเป็นผู้ที่มีสิทธิได้รับเงินค่าตอบแทนตามระเบียบ ประกาศ ข้อบังคับ หลักเกณฑ์ เงื่อนไข วิธีการ และอัตราที่กำหนดไว้ทุกประการ แต่หากข้าพเจ้าแสดงข้อมูลอันเป็นเท็จหรือได้รับเงินค่าตอบแทนดังกล่าวไม่ชอบด้วยกฎหมาย ข้าพเจ้ายินดีรับผิดชอบชดใช้เงินคืนให้แก่องค์กรปกครองส่วนท้องถิ่นที่จ่ายเงิน ตามจำนวนเงินที่ได้รับพร้อมดอกเบี้ยที่กฎหมายกำหนด';
function review(n,title){return '<section class="review"><strong>('+n+') '+title+'</strong><p>□ เห็นควรอนุมัติ &nbsp; □ ไม่เห็นควรอนุมัติ</p><p>ความเห็น ........................................................<br>....................................................................</p><div class="review-sign">ลงชื่อ .....................................................<br>(........................................................)<br>ตำแหน่ง ................................................<br>วันที่ .....................................................</div></section>';}
export function printableDocument(record,{person=null,facility=null}={}){
 if(!['chor11_annual','chor11_monthly'].includes(record.form_code))throw new Error('แบบพิมพ์ไม่เปิดใช้งาน');
 const f={...record.form_data};if(person)Object.assign(f,{full_name:person.full_name,position_name:person.position_name,position_level:person.position_level,employment_type:person.employment_type,facility_name:facility?.facility_name||facility?.short_name||person.facility_code});
 const identity='<p>ข้าพเจ้า '+fill(f.full_name)+' ตำแหน่ง '+fill(f.position_name)+'</p><p>ระดับ '+fill(f.position_level)+' ประเภทการจ้าง '+fill(f.employment_type)+'</p><p>ปฏิบัติงานในหน่วยบริการ '+fill(f.facility_name)+'</p>';
 const period='<p>ช่วงปฏิบัติงานตั้งแต่ '+fill(date(f.work_date_from))+' ถึง '+fill(date(f.work_date_to))+'</p>';
 let body,title;
 if(record.form_code==='chor11_annual'){
 title='แบบคำขอรับเงินค่าตอบแทนประจำปี';
 const categories=['ค่าตอบแทนการปฏิบัติงานของเจ้าหน้าที่','ค่าตอบแทนการปฏิบัติงานคลินิกพิเศษนอกเวลาราชการ','ค่าตอบแทนเวรบ่ายหรือเวรดึกของพยาบาล','ค่าตอบแทนการชันสูตรพลิกศพ','ค่าตอบแทนแพทย์ที่ปฏิบัติงานในพื้นที่พิเศษ','ค่าตอบแทนกรณีไม่ทำเวชปฏิบัติส่วนตัว','ค่าตอบแทนการปฏิบัติงานด้านส่งเสริมสุขภาพและป้องกันโรค','ค่าเบี้ยเลี้ยงเหมาจ่ายสำหรับเจ้าหน้าที่ที่ปฏิบัติงานในหน่วยบริการสาธารณสุข','ค่าตอบแทนอื่น'];
 body='<article class="sheet annual"><h1>แบบคำขอรับเงินค่าตอบแทนเจ้าหน้าที่ที่ปฏิบัติงานให้แก่หน่วยบริการสาธารณสุข<br>ขององค์กรปกครองส่วนท้องถิ่น</h1><div class="right">เขียนที่ '+fill(f.written_at||f.facility_name)+'<br>วันที่ '+fill(date(f.request_date))+'</div><p>เรื่อง ขอรับเงินค่าตอบแทน<br>เรียน นายกเทศมนตรีเมืองเขลางค์นคร</p>'+identity+period+'<p>ระยะเวลาปฏิบัติงาน '+fill(f.service_years??0)+' ปี '+fill(f.service_months??0)+' เดือน '+fill(f.service_days??0)+' วัน</p><p>ที่อยู่ติดต่อ '+fill(f.contact_address)+'</p><p>ใบอนุญาตประกอบวิชาชีพประเภท '+fill(f.license_type)+'<br>เลขที่ '+fill(f.license_number)+'</p><p>มีความประสงค์ขอรับเงินค่าตอบแทนตามข้อ 4 แห่งระเบียบกระทรวงมหาดไทย ว่าด้วยเงินค่าตอบแทนเจ้าหน้าที่ที่ปฏิบัติงานให้แก่หน่วยบริการสาธารณสุขขององค์กรปกครองส่วนท้องถิ่น พ.ศ. 2566 ประจำปีงบประมาณ '+esc(record.fiscal_year)+' ดังนี้</p><div class="categories">'+categories.map((c,i)=>'<div>'+(i===7?'☑':'□')+' ('+(i+1)+') '+esc(c)+'</div>').join('')+'</div><p>อัตราค่าตอบแทน '+fill(money(f.monthly_rate))+' บาทต่อเดือน</p><p>หมายเหตุ '+fill(f.note)+'</p>'+footer(1)+'</article><article class="sheet annual"><p>'+certification+'</p><p>จึงเรียนมาเพื่อโปรดพิจารณาอนุมัติ</p>'+signature(f)+'<h2>ผลการพิจารณาของผู้บังคับบัญชาและคณะกรรมการฯ</h2><div class="reviews">'+review(1,'ผู้บังคับบัญชา')+review(2,'หัวหน้าหน่วยบริการสาธารณสุข')+review(3,'คณะกรรมการพิจารณาค่าตอบแทน')+review(4,'คณะกรรมการจ่ายเงินค่าตอบแทน')+'</div><section class="review approver"><strong>(5) ผู้มีอำนาจอนุมัติ</strong><p>□ อนุมัติ &nbsp; □ ไม่อนุมัติ &nbsp; ความเห็น ........................................................</p><div class="review-sign">ลงชื่อ ........................................................<br>(........................................................)<br>วันที่ ........................................................</div></section><p class="small">หมายเหตุ: ผู้พิจารณาอาจขอเอกสารประกอบเพิ่มเติมได้ • จัดทำคำขอ 1 รายการต่อคนต่อปีงบประมาณ</p>'+footer(2)+'</article>';
 }else{
 title='ใบขอรับเงินค่าตอบแทนเบี้ยเลี้ยงเหมาจ่ายรายเดือน';const month=new Date(record.period_month+'T00:00:00').toLocaleDateString('th-TH',{month:'long',year:'numeric'});
 body='<article class="sheet monthly"><h1>ใบขอรับเงินค่าตอบแทนเบี้ยเลี้ยงเหมาจ่ายสำหรับเจ้าหน้าที่<br>ที่ปฏิบัติงานในหน่วยบริการ สังกัดเทศบาลเมืองเขลางค์นคร</h1><div class="right">หน่วยบริการ '+fill(f.facility_name)+'<br>ประจำเดือน '+fill(month)+'<br>วันที่ยื่น '+fill(date(f.request_date))+'</div>'+identity+'<p>ปีงบประมาณ '+fill(record.fiscal_year)+'</p><h2>ข้อมูลการปฏิบัติงานและจำนวนเงินที่ขอรับ</h2>'+period+'<table><thead><tr><th>อัตราต่อเดือน (บาท)</th><th>วันปฏิบัติงาน</th><th>วันลา/ขาดงาน</th><th>จำนวนเงินที่ขอเบิก (บาท)</th></tr></thead><tbody><tr><td>'+money(f.monthly_rate)+'</td><td>'+esc(f.work_days??0)+'</td><td>'+esc(f.leave_days??0)+'</td><td>'+money(f.total_amount)+'</td></tr></tbody></table><p>หมายเหตุ '+fill(f.note)+'</p><p class="certify">ข้าพเจ้าขอรับรองว่าข้อมูลดังกล่าวเป็นความจริงทุกประการ และหากมีการเรียกเงินคืน ข้าพเจ้าขอรับผิดชอบคืนเงินแต่เพียงผู้เดียว</p>'+signature(f,'ผู้ขอรับเงิน')+footer(1)+'</article>';
 }
 const font=new URL('../../assets/fonts/',import.meta.url).href;
 return '<!doctype html><html lang="th"><head><meta charset="utf-8"><title>'+esc(title)+'</title><style>@font-face{font-family:Sarabun;src:url("'+font+'Sarabun-Regular.ttf")}@font-face{font-family:Sarabun;src:url("'+font+'Sarabun-Bold.ttf");font-weight:700}@page{size:A4;margin:0}*{box-sizing:border-box}body{margin:0;background:#e9edef;color:#000;font-family:Sarabun,"Angsana New",sans-serif;font-size:12pt;line-height:1.45}.sheet{width:210mm;min-height:297mm;padding:12mm 16mm 15mm;margin:18px auto;background:white;position:relative;break-after:page}.sheet:last-child{break-after:auto}h1{font-size:14pt;text-align:center;line-height:1.5;margin:0 0 5mm}h2{font-size:12pt;text-align:center;margin:5mm 0}p{margin:3mm 0;overflow-wrap:anywhere}.right{text-align:right;overflow-wrap:anywhere}.fill{display:inline;border-bottom:1px dotted #555;padding:0 2mm;white-space:pre-wrap}.categories{font-size:11pt;line-height:1.7}.signature{text-align:center;margin:6mm 0 5mm 40%;font-size:11pt}.reviews{display:grid;grid-template-columns:1fr 1fr;gap:3mm}.review{border:1px solid #444;padding:3mm;font-size:10pt;break-inside:avoid}.review p{margin:2mm 0}.review-sign{text-align:center}.approver{margin-top:3mm}.small,footer{font-size:8pt}footer{position:absolute;bottom:6mm;left:16mm;right:16mm;text-align:center}table{width:100%;border-collapse:collapse;margin:6mm 0}th,td{border:1px solid #000;padding:3mm;text-align:center;font-size:11pt}.certify{margin-top:12mm}.toolbar{position:sticky;top:0;background:#fff;padding:10px;text-align:center;z-index:1}.toolbar button{padding:10px 16px;font:16px sans-serif}@media print{body{background:white}.toolbar{display:none}.sheet{margin:0;box-shadow:none}}@media screen and (max-width:800px){.sheet{margin:12px 0}}</style></head><body><div class="toolbar"><button id="print-button">พิมพ์ / บันทึก PDF</button></div><main>'+body+'</main></body></html>';
}
